import { describe, expect, it } from 'vitest';

// The generator is a Node ESM script. Its pure validators are imported here so
// inventory failures stay covered without running image conversion in unit tests.
// @ts-expect-error The build pipeline is JavaScript and intentionally has no runtime TypeScript dependency.
import { allVisualDomains, responsiveVisualDomains, validateExactInventory, validateGeneratedFreshness } from '../../scripts/panelVisualAssetPipeline.mjs';

interface VisualDomainContract {
  name: string;
  manifestType: string;
  variants: Array<{ name: string }>;
}

describe('panel visual asset pipeline validation', () => {
  it('rejects missing, duplicate, and unexpected source identities', () => {
    expect(() => validateExactInventory(['a.png'], ['a.png', 'b.png'], 'fixture')).toThrow(/missing/i);
    expect(() => validateExactInventory(['a.png', 'a.png'], ['a.png'], 'fixture')).toThrow(/duplicate/i);
    expect(() => validateExactInventory(['a.png', 'b.png'], ['a.png'], 'fixture')).toThrow(/unexpected/i);
  });

  it('rejects stale generated bytes and accepts exact deterministic output', () => {
    const encoder = new TextEncoder();
    expect(() => validateGeneratedFreshness(encoder.encode('old'), encoder.encode('new'), 'asset.webp')).toThrow(/stale/i);
    expect(() => validateGeneratedFreshness(encoder.encode('same'), encoder.encode('same'), 'asset.webp')).not.toThrow();
  });

  it('covers combat, war, and map masters with mobile and display variants', () => {
    const responsiveDomains = responsiveVisualDomains as VisualDomainContract[];
    expect(responsiveDomains.map((domain) => domain.name)).toEqual([
      'combat-background',
      'combat-character',
      'war-background',
      'war-force',
      'map',
    ]);
    expect(allVisualDomains).toHaveLength(7);
    for (const domain of responsiveDomains) {
      expect(domain.variants.map((variant) => variant.name)).toEqual(['mobile', 'display']);
      expect(domain.manifestType).toBe('ResponsiveVisualAssetManifest');
    }
  });
});
