import type { OpeningCharacterOptions } from '../../engine/types';

export const threeKingdomsCharacterOptions: OpeningCharacterOptions = {
  birthOrigins: [
    { id: 'birth_han_clan_branch', label: '宗室支脉', description: '汉室远支，名分尚在，实权未必可靠。' },
    { id: 'birth_great_clan', label: '世家大族', description: '累世经学或官宦之家，门第可用也会成束缚。' },
    { id: 'birth_local_gentry', label: '郡县士族', description: '地方清望之家，熟悉乡里与官府规矩。' },
    { id: 'birth_powerful_household', label: '豪强大族', description: '庄园、部曲、人脉深厚，地方影响更重。' },
    { id: 'birth_poor_scholar', label: '寒门士子', description: '读书识字而门第微薄，需要机会改命。' },
    { id: 'birth_good_family', label: '良家子', description: '平民良家出身，尚有清白户籍和乡里根脚。' },
    { id: 'birth_merchant_family', label: '商贾之家', description: '有钱货与道路消息，却常受士人轻视。' },
    { id: 'birth_craft_or_medicine', label: '匠医之家', description: '凭技艺立身，能接触市井与豪门。' },
    { id: 'birth_border_martial', label: '边郡武家', description: '边地军旅传统，熟悉兵事和险恶局面。' },
    { id: 'birth_tenant_or_poor', label: '佃户贫民', description: '生计艰难，乱世压力最先落到身上。' },
    { id: 'birth_displaced_household', label: '流民遗户', description: '家族根脚残破，缺少庇护，也少受旧关系束缚。' },
  ],
  identities: [
    { id: 'identity_wild_scholar', label: '在野士人', description: '尚未出仕，可投名主，也可自立声名。' },
    { id: 'identity_county_clerk', label: '郡县小吏', description: '身在官府基层，消息灵通却地位有限。' },
    { id: 'identity_county_magistrate', label: '县令长', description: '一县之主，名义掌民政刑狱，实际受郡府、豪族与乱兵牵制。' },
    { id: 'identity_governor', label: '太守', description: '郡国长官，握地方军政名分，但乱世中权力常被豪强、兵乱和朝廷命令撕扯。' },
    { id: 'identity_court_minister', label: '朝中重臣', description: '身在京师权力场，名望与风险并重，容易卷入外戚、宦官与诸侯角力。' },
    { id: 'identity_military_officer', label: '军中将校', description: '有军职或兵权线索，能调动部属，却也必须面对军令、粮饷和派系牵制。' },
    { id: 'identity_ranger', label: '游侠', description: '重义气、熟江湖，容易卷入冲突。' },
    { id: 'identity_retainer', label: '门客幕僚', description: '依附豪门或诸侯，以才智、人情求进。' },
    { id: 'identity_local_militia', label: '乡勇募兵', description: '被战乱推到兵事边缘，可能立功也可能送命。' },
    { id: 'identity_merchant_traveler', label: '商旅', description: '往来道路，懂货物流通与各地风声。' },
    { id: 'identity_physician', label: '医者方士', description: '能进出不同阶层，也容易被疑为异术之人。' },
    { id: 'identity_yellow_turban', label: '黄巾信众', description: '太平道牵连在身，既是庇护也是危险。' },
    { id: 'identity_refugee', label: '流亡者', description: '无固定依附，首要目标是活下去。' },
    { id: 'identity_household_troop', label: '豪族部曲', description: '受豪族豢养驱使，熟悉地方私兵体系。' },
    { id: 'identity_palace_involved', label: '宫廷牵连者', description: '与京师、宦门或外戚有旧线，风险极高。' },
  ],
  abilityPresets: [
    { id: 'balanced', label: '均衡型', scores: { 武力: 52, 统率: 52, 智力: 52, 政治: 52, 魅力: 52, 机运: 50 } },
    { id: 'martial', label: '武勇型', scores: { 武力: 70, 统率: 56, 智力: 44, 政治: 38, 魅力: 50, 机运: 50 } },
    { id: 'commander', label: '统率型', scores: { 武力: 56, 统率: 70, 智力: 50, 政治: 44, 魅力: 48, 机运: 50 } },
    { id: 'strategist', label: '谋略型', scores: { 武力: 38, 统率: 50, 智力: 72, 政治: 56, 魅力: 46, 机运: 50 } },
    { id: 'political', label: '政治型', scores: { 武力: 36, 统率: 44, 智力: 58, 政治: 72, 魅力: 52, 机运: 50 } },
    { id: 'charismatic', label: '人望型', scores: { 武力: 44, 统率: 50, 智力: 50, 政治: 56, 魅力: 72, 机运: 50 } },
  ],
  traits: [
    {
      id: 'trait_archery_horse',
      label: '弓马娴熟',
      description: '熟悉骑射与野外奔驰。',
      source: 'opening',
      rarity: 'green',
      promptHint: '涉及骑乘、追逐、射猎、侦骑或边地行军时，可以给主角更可信的发挥空间。',
    },
    {
      id: 'trait_military_books',
      label: '熟读兵书',
      description: '读过兵法与军事旧事。',
      source: 'opening',
      rarity: 'green',
      promptHint: '遇到军阵、守城、伏击或局势分析时，主角能提出有条理但仍需现实验证的判断。',
    },
    {
      id: 'trait_county_clerk',
      label: '县中文书',
      description: '熟悉县中簿籍、公文和小吏办事规矩。',
      source: 'opening',
      rarity: 'white',
      promptHint: '涉及户籍、赋役、官文、县衙流程时，主角更容易看出漏洞和门道。',
    },
    {
      id: 'trait_street_ears',
      label: '街巷耳目',
      description: '熟悉市井传闻与街巷人情。',
      source: 'opening',
      rarity: 'white',
      promptHint: '打听消息、分辨流言、接触市井小人物时更自然，但不等于消息必然准确。',
    },
    {
      id: 'trait_old_gentry_ties',
      label: '豪门旧识',
      description: '与地方豪族或名门有旧交线索。',
      source: 'opening',
      rarity: 'blue',
      promptHint: '可以开启拜访、求荐、借势或被牵连的剧情，不应直接等于无条件支持。',
    },
    {
      id: 'trait_observant',
      label: '善察人心',
      description: '能从言行细节判断他人真实态度。',
      source: 'opening',
      rarity: 'blue',
      promptHint: '社交、谈判、识破敷衍和观察情绪时更敏锐，但仍可能被高手误导。',
    },
    {
      id: 'trait_bold',
      label: '胆气过人',
      description: '临危不容易退缩。',
      source: 'opening',
      rarity: 'green',
      promptHint: '面对威胁、突发冲突或危险决断时更能稳住场面，但也可能招致更大风险。',
    },
    {
      id: 'trait_generous',
      label: '轻财好义',
      description: '愿意用钱财和行动维系义气。',
      source: 'opening',
      rarity: 'green',
      promptHint: '结交游侠、救济困人、赢得短期人心时有帮助，但会消耗个人钱财。',
    },
    {
      id: 'trait_careful',
      label: '谨慎自守',
      description: '遇事先观察，不轻易暴露底牌。',
      source: 'opening',
      rarity: 'green',
      promptHint: '未知风险、权力试探和敌意接触中，主角默认更倾向试探、留后路。',
    },
    {
      id: 'trait_ranger_fame',
      label: '游侠名声',
      description: '在乡里或道路上有一点任侠之名。',
      source: 'opening',
      rarity: 'blue',
      promptHint: '容易引来求助、冲突和江湖式牵连，也会让官府或豪强更警惕。',
    },
    {
      id: 'trait_basic_medicine',
      label: '粗通医药',
      description: '懂得止血、辨药和寻常病伤处理。',
      source: 'opening',
      rarity: 'white',
      promptHint: '伤病、救人、行旅照护时可发挥作用，但不能替代名医或神效治疗。',
    },
    {
      id: 'trait_trade_routes',
      label: '熟悉商路',
      description: '知道道路、货物流向和沿途风声。',
      source: 'opening',
      rarity: 'white',
      promptHint: '旅行、贸易、避险、辨认商队消息时更可靠，但商路变化仍受战乱影响。',
    },
    {
      id: 'trait_eloquent',
      label: '能言善辩',
      description: '说理清楚，善于临场找出可被接受的说法。',
      source: 'opening',
      rarity: 'green',
      promptHint: '游说、辩解、斡旋、安抚人心时更有发挥，但不能凭空说服立场极硬的人。',
    },
    {
      id: 'trait_clan_trust',
      label: '乡党信重',
      description: '在同乡、宗族或熟人圈中较容易被信任。',
      source: 'opening',
      rarity: 'blue',
      promptHint: '召集乡人、求取担保、避开误会时有分量，但离开熟人范围后作用减弱。',
    },
    {
      id: 'trait_grain_ledger',
      label: '辨识粮草',
      description: '能看出粮仓、车队、军粮账面里的大致真假。',
      source: 'opening',
      rarity: 'green',
      promptHint: '涉及粮秣、军需、灾荒和后勤时，主角能发现不寻常之处。',
    },
    {
      id: 'trait_waterways',
      label: '识得水性',
      description: '懂得渡口、水势和舟船行旅的基本门道。',
      source: 'opening',
      rarity: 'white',
      promptHint: '渡河、避水路风险、打听船家消息时更顺手，但不等于精通水战。',
    },
    {
      id: 'trait_border_scout',
      label: '边地识途',
      description: '熟悉边郡道路、关隘风声和胡汉杂处的规矩。',
      source: 'opening',
      rarity: 'blue',
      promptHint: '边塞、关隘、骑兵、部族往来剧情中更容易找到可行路径。',
    },
    {
      id: 'trait_household_retinue',
      label: '部曲旧缘',
      description: '与某些家兵、门客或旧部有可追索的交情。',
      source: 'opening',
      rarity: 'blue',
      promptHint: '可引出投奔、借人、旧部相认或旧怨重现，不应直接变成免费兵力。',
    },
    {
      id: 'trait_scholarly_repute',
      label: '士林清望',
      description: '在读书人圈子里已有可被提起的清名。',
      source: 'opening',
      rarity: 'red',
      promptHint: '举荐、清议、名士往来和政治站队中影响很大，也会引来审视与敌意。',
    },
    {
      id: 'trait_commander_disciple',
      label: '名将门生',
      description: '曾受名将指点、收留或门下提携。',
      source: 'opening',
      rarity: 'red',
      promptHint: '军中履历、派系、人脉和敌对势力都会因此被牵动，影响重但风险也重。',
    },
    {
      id: 'trait_palace_whisper',
      label: '宫禁旧线',
      description: '与京师、宦门、外戚或宫中传闻有隐秘旧线。',
      source: 'opening',
      rarity: 'red',
      promptHint: '可开启高风险权力信息，但每次使用都可能带来追查、试探或误判。',
    },
    {
      id: 'trait_craft_eye',
      label: '匠作眼力',
      description: '能看出兵器、器具、车马修造的粗细优劣。',
      source: 'opening',
      rarity: 'white',
      promptHint: '修理、采买、辨别粗劣装备和与工匠交流时更可信。',
    },
    {
      id: 'trait_mountain_paths',
      label: '山泽识途',
      description: '对山路、林泽、猎径和藏身处有经验。',
      source: 'opening',
      rarity: 'green',
      promptHint: '逃亡、绕行、搜寻山中据点或避开官道时更容易找到办法。',
    },
    {
      id: 'trait_patient_listener',
      label: '善听微言',
      description: '愿意耐心听完旁人的细碎话语，从中抓住关键。',
      source: 'opening',
      rarity: 'green',
      promptHint: '问话、审讯、安抚、收集零散线索时更容易得到真实信息。',
    },
    {
      id: 'trait_ritual_manners',
      label: '礼法周旋',
      description: '懂得士人、官府、宗族之间的礼节边界。',
      source: 'opening',
      rarity: 'green',
      promptHint: '拜访、求见、宴饮、宗族议事中更不容易失礼，也更容易看懂暗示。',
    },
    {
      id: 'trait_market_arithmetic',
      label: '市井算筹',
      description: '会盘算买卖、债务、物价和小额账目。',
      source: 'opening',
      rarity: 'white',
      promptHint: '交易、雇人、估价、识破简单账目猫腻时可发挥作用。',
    },
    {
      id: 'trait_camp_customs',
      label: '营中旧例',
      description: '熟悉军营中上下相处、分粮执勤和口令规矩。',
      source: 'opening',
      rarity: 'green',
      promptHint: '进入军营、辨认军令、与士卒打交道时更自然，也更知道哪些事不能乱碰。',
    },
    {
      id: 'trait_hidden_patience',
      label: '忍辱藏锋',
      description: '能在受辱、受压或被轻视时暂且压住锋芒。',
      source: 'opening',
      rarity: 'blue',
      promptHint: '卧底、寄人篱下、政治试探或弱势开局中更容易等待机会反转。',
    },
  ],  hiddenAbilityKeys: ['机运'],
};
