import type { WorldlineKnowledgeCard } from '../../engine/types';
import {
  THREE_KINGDOMS_MAJOR_EVENT_MANIFEST,
  type ThreeKingdomsMajorEventManifestEntry,
} from './knowledgeBaseMajorEventManifest';

interface Batch2EventInput {
  id: string;
  manifestId: string;
  title?: string;
  summary: string;
  relatedNpcNames: string[];
  relatedPlaceIds: string[];
  relatedTags?: string[];
  structuralPressure: string;
  contradictionHint: string;
}

const manifestById = new Map(
  THREE_KINGDOMS_MAJOR_EVENT_MANIFEST.map((entry) => [entry.id, entry] as const),
);

function requireManifestEntry(manifestId: string): ThreeKingdomsMajorEventManifestEntry {
  const entry = manifestById.get(manifestId);
  if (!entry) {
    throw new Error(`Missing KnowledgeBase manifest entry: ${manifestId}`);
  }
  return entry;
}

function historicalEventCard(input: Batch2EventInput): WorldlineKnowledgeCard {
  const manifest = requireManifestEntry(input.manifestId);
  const start = manifest.historicalWindow.earliest ?? manifest.historicalWindow.typical;
  const end = manifest.historicalWindow.latest ?? manifest.historicalWindow.typical;
  return {
    id: input.id,
    worldBookId: 'threeKingdoms',
    kind: 'event',
    title: input.title ?? manifest.title,
    summary: input.summary,
    timeRange: { start, end },
    relatedNpcNames: input.relatedNpcNames,
    relatedFactionIds: [],
    relatedPlaceIds: input.relatedPlaceIds,
    relatedTags: [...new Set([
      manifest.title,
      ...manifest.aliases,
      ...(input.relatedTags ?? []),
    ])],
    importance: 'major',
    strictness: 'strict',
    contradictionHint: `本局边界：${input.contradictionHint}`,
    sourceLabel: '《三国志》《后汉书》《资治通鉴》历史锚点整理',
    historicalEvent: {
      historicalWindow: { ...manifest.historicalWindow },
      structuralPressure: input.structuralPressure,
      divergencePolicy: { ...manifest.divergencePolicy },
    },
  };
}

/**
 * KnowledgeBase Batch 2：184—234 年重大事件链补齐。
 *
 * 这些卡只提供史实锚点与偏转边界，不触发事件，也不直接写入本局状态。
 * 时间窗和偏转政策统一取自 manifest，避免施工清单与运行卡片各自维护。
 */
export const THREE_KINGDOMS_KNOWLEDGE_BASE_BATCH_2_MAJOR_EVENTS: WorldlineKnowledgeCard[] = [
  historicalEventCard({
    id: 'tk3k_192_dongzhuo_death',
    manifestId: 'tk3k_manifest_192_dongzhuo_death',
    summary: '初平三年（192），王允、吕布等在长安诛杀董卓。董卓集团的中枢骤然瓦解，但王允未能妥善收束凉州军余部，赦免与军权安排的失败很快把朝廷推入下一轮冲突。',
    relatedNpcNames: ['董卓', '王允', '吕布', '李傕', '郭汜'],
    relatedPlaceIds: ['region_sili'],
    relatedTags: ['初平三年', '长安权力真空', '凉州军余部'],
    structuralPressure: '董卓集团若以其他方式失势，京师军权、凉州军安置与汉廷控制权仍会形成新的权力真空。',
    contradictionHint: '若董卓在本局仍存活、已归降或由另一势力控制京师，不得照搬王允吕布刺董卓及其固定后果。',
  }),
  historicalEventCard({
    id: 'tk3k_192_lijue_guosi_changan',
    manifestId: 'tk3k_manifest_192_lijue_guosi_changan',
    summary: '董卓死后，李傕、郭汜、张济等采纳贾诩建议，收拢凉州军攻入长安；王允被杀、吕布出走，献帝再受军阀控制。其后李郭内斗进一步破坏关中秩序，并促成天子东归。',
    relatedNpcNames: ['李傕', '郭汜', '张济', '贾诩', '王允', '吕布', '刘协'],
    relatedPlaceIds: ['region_sili', 'region_liangzhou'],
    relatedTags: ['李郭之乱', '献帝受制', '关中残破'],
    structuralPressure: '未获安置的旧军、京师粮秣和皇帝控制权会继续驱动关中武装冲突。',
    contradictionHint: '若凉州军已被收编、遣散或长安控制者不同，只保留旧军安置与皇权争夺的结构压力，不得换名复演李郭攻城。',
  }),
  historicalEventCard({
    id: 'tk3k_193_xuzhou_campaign',
    manifestId: 'tk3k_manifest_193_xuzhou_campaign',
    summary: '193—194 年，曹操以父亲曹嵩在徐州境内遇害为直接缘由两度攻陶谦。徐州多地遭受严重杀掠与人口流离，具体责任和数字见诸不同记载；田楷、刘备等曾赴援，兖州生变迫使曹操回军。',
    relatedNpcNames: ['曹操', '曹嵩', '陶谦', '田楷', '刘备', '吕布'],
    relatedPlaceIds: ['region_xuzhou', 'region_yanzhou'],
    relatedTags: ['曹操伐陶谦', '徐州杀掠', '人口流离'],
    structuralPressure: '徐兖之间的复仇、粮道、流民与地方归属矛盾会持续影响两州关系。',
    contradictionHint: '若曹嵩未死、曹陶关系或徐州控制线已改变，不得强制发动同样战争；杀戮规模也不得把争议记载写成精确本局事实。',
  }),
  historicalEventCard({
    id: 'tk3k_194_xuzhou_succession',
    manifestId: 'tk3k_manifest_194_xuzhou_succession',
    summary: '《三国志·先主传》记陶谦临终嘱麋竺称刘备可安徐州；陶谦死后，麋竺率州人迎刘备，刘备经陈登、孔融劝说后领徐州。“三让徐州”是后世文学对推辞过程的集中组织，不是三次正式政权交割。',
    relatedNpcNames: ['陶谦', '刘备', '麋竺', '陈登', '孔融', '袁术'],
    relatedPlaceIds: ['region_xuzhou'],
    relatedTags: ['刘备领徐州', '徐州权力交接', '三让徐州', '陶谦三让徐州', '三让文学纠偏'],
    structuralPressure: '州牧去世后的官吏、豪族、军队和民众需要重新选择可维持徐州秩序的权力核心。',
    contradictionHint: '若陶谦、刘备或徐州归属已改变，只能依据本局重新处理继承危机；不得为了“三让徐州”名目反复安排让州。',
  }),
  historicalEventCard({
    id: 'tk3k_194_yanzhou_war',
    manifestId: 'tk3k_manifest_194_yanzhou_war',
    summary: '曹操再征徐州时，陈宫、张邈等迎吕布入兖州，多数郡县响应，曹操一度仅守住鄄城、范、东阿等据点。双方经历濮阳等地的长期争夺与饥荒，曹操随后逐步收复兖州，吕布转往徐州。',
    relatedNpcNames: ['曹操', '吕布', '陈宫', '张邈', '荀彧', '程昱'],
    relatedPlaceIds: ['region_yanzhou', 'region_xuzhou'],
    relatedTags: ['吕布袭兖州', '曹吕兖州之战', '濮阳之战'],
    structuralPressure: '主力远征造成的后方空虚、地方士人离心和粮荒会持续威胁兖州控制。',
    contradictionHint: '若曹操未远征、吕布阵营或兖州郡县态度已改变，不得照搬“几乎全州响应”的原史实格局。',
  }),
  historicalEventCard({
    id: 'tk3k_195_emperor_east_return',
    manifestId: 'tk3k_manifest_195_emperor_east_return',
    summary: '195 年李傕、郭汜内斗后，献帝在杨奉、董承等护送下离开长安东归。车驾沿途遭追击、断粮和护驾诸军争权，至 196 年才回到残破洛阳；朝廷缺乏粮饷与稳定军力，为曹操奉迎迁许创造条件。',
    relatedNpcNames: ['刘协', '李傕', '郭汜', '杨奉', '董承', '张济', '曹操'],
    relatedPlaceIds: ['region_sili'],
    relatedTags: ['天子东归', '洛阳困局', '护驾诸军'],
    structuralPressure: '失去稳定供给和军队的汉廷需要在护驾武装、地方诸侯与京师重建之间寻找依托。',
    contradictionHint: '若献帝所在地、护驾者或汉廷供给已被本局改变，迁徙路线与最终依托必须服从本局，不得自动迁许。',
  }),
  historicalEventCard({
    id: 'tk3k_197_yuanshu_emperor',
    manifestId: 'tk3k_manifest_197_yuanshu_emperor',
    summary: '建安二年（197），袁术在寿春僭号，建号“仲氏”。此举使其与汉廷名义及周边诸侯关系急剧恶化，原有地盘又承受征敛、战争与离叛压力；袁术随后败亡并非仅由一次战役决定。',
    relatedNpcNames: ['袁术', '刘协', '孙策', '吕布', '曹操', '刘备'],
    relatedPlaceIds: ['region_yangzhou', 'region_yuzhou'],
    relatedTags: ['袁术僭号', '仲氏', '寿春称帝'],
    structuralPressure: '割据者的合法性诉求、财政征敛和盟友承认仍会改变淮南政治关系。',
    contradictionHint: '若袁术势力、玉玺传承或称帝条件已改变，可以不发生或转化为其他合法性冲突，不得强制建立仲氏政权。',
  }),
  historicalEventCard({
    id: 'tk3k_197_wancheng',
    manifestId: 'tk3k_manifest_197_wancheng',
    summary: '197 年曹操南征宛城，张绣先降后反，曹军猝败，曹昂、典韦、曹安民等死。贾诩参与张绣决策；此后曹张仍有反复交战，至 199 年张绣才再次归降，宛城并非一战即稳定易手。',
    relatedNpcNames: ['曹操', '张绣', '贾诩', '典韦', '曹昂', '曹安民'],
    relatedPlaceIds: ['region_jingzhou', 'region_yuzhou'],
    relatedTags: ['曹操征张绣', '淯水之战', '宛城兵变'],
    structuralPressure: '南阳门户、降军安置与首领安全感会持续影响曹操集团的南线。',
    contradictionHint: '若张绣已归属他方、宛城控制或曹操亲属命运已改变，不得复刻先降后叛及固定死亡名单。',
  }),
  historicalEventCard({
    id: 'tk3k_198_xiapi',
    manifestId: 'tk3k_manifest_198_xiapi',
    summary: '198 年曹操与刘备进围下邳，吕布集团在久围、决水与内部离心下崩溃。侯成、宋宪、魏续等控制吕布及陈宫、高顺，战后吕布、高顺、陈宫被处死。“白门楼”是著名文学场景名，不等于全部细节均有同等史料依据。',
    relatedNpcNames: ['曹操', '刘备', '吕布', '陈宫', '高顺', '侯成', '宋宪', '魏续'],
    relatedPlaceIds: ['region_xuzhou'],
    relatedTags: ['曹操擒吕布', '下邳围城', '白门楼纠偏'],
    structuralPressure: '徐州控制、围城供给和吕布集团内部信任危机会继续决定其存亡。',
    contradictionHint: '若吕布已离开徐州、下邳控制或参战联盟改变，不得安排相同被俘与处刑；白门楼对白也不能当成本局必然事实。',
  }),
  historicalEventCard({
    id: 'tk3k_199_yijing',
    manifestId: 'tk3k_manifest_199_yijing',
    summary: '袁绍与公孙瓒长期争夺河北、幽州，至 199 年围破易京。公孙瓒在堡垒体系失守后败亡，袁绍由此基本控制河北北部；边郡军政、乌桓关系与旧部归属仍需继续整合。',
    relatedNpcNames: ['袁绍', '公孙瓒', '麹义', '田豫'],
    relatedPlaceIds: ['region_jizhou', 'region_youzhou'],
    relatedTags: ['袁绍灭公孙瓒', '易京楼', '河北统一'],
    structuralPressure: '河北核心势力与幽州边军之间的控制、粮道和归附问题仍会重塑北方格局。',
    contradictionHint: '若公孙瓒或袁绍阵营已被改写、易京未建或幽州另有控制者，不得照搬围城与公孙瓒败亡。',
  }),
  historicalEventCard({
    id: 'tk3k_200_guandu_campaign',
    manifestId: 'tk3k_manifest_200_guandu',
    title: '200 年官渡完整战役链',
    summary: '官渡不是单场决斗：袁绍南进前后经历白马、延津交锋，曹操与袁军在官渡长期相持并承受粮运压力；许攸离袁投曹后，曹操袭乌巢辎重，袁军指挥与士气崩解。各阶段都依赖人物、情报和粮道。',
    relatedNpcNames: ['曹操', '袁绍', '许攸', '荀攸', '关羽', '颜良', '文丑', '淳于琼', '张郃', '高览'],
    relatedPlaceIds: ['region_yuzhou', 'region_jizhou', 'region_yanzhou'],
    relatedTags: ['官渡完整事件链', '白马', '延津', '乌巢', '粮道'],
    structuralPressure: '袁曹争夺中原的兵力、粮运、情报和集团内部协调压力仍会存在。',
    contradictionHint: '若袁曹格局、许攸归属、乌巢粮营或关键将领命运已改变，不得强制火烧乌巢或复制史实胜负。',
  }),
  historicalEventCard({
    id: 'tk3k_202_yuan_succession',
    manifestId: 'tk3k_manifest_202_yuan_succession',
    summary: '袁绍 202 年死后，审配、逢纪等拥袁尚，袁谭不服，继承内战削弱河北。曹操利用其分裂，204 年取邺，205 年破袁谭；袁尚、袁熙最终逃往乌桓，207 年又奔辽东并被公孙康所杀。',
    relatedNpcNames: ['袁绍', '袁谭', '袁尚', '袁熙', '审配', '逢纪', '曹操', '公孙康'],
    relatedPlaceIds: ['region_jizhou', 'region_qingzhou', 'region_youzhou'],
    relatedTags: ['袁谭袁尚之争', '邺城之战', '曹操平河北'],
    structuralPressure: '河北继承合法性、州郡站队与外部势力干预会在袁绍身后继续发酵。',
    contradictionHint: '若袁绍继承安排、诸子存亡或河北控制线不同，不得强行制造袁谭袁尚内战及相同终局。',
  }),
  historicalEventCard({
    id: 'tk3k_207_wuhuan',
    manifestId: 'tk3k_manifest_207_wuhuan',
    summary: '207 年曹操采纳郭嘉等进言北征乌桓，在田畴引导下经卢龙塞险道出兵，于白狼山击败蹋顿等部；袁熙、袁尚逃往辽东。战后乌桓人口、骑兵和边郡秩序被重新整合，北方统一仍含边疆迁徙代价。',
    relatedNpcNames: ['曹操', '郭嘉', '田畴', '蹋顿', '袁熙', '袁尚', '公孙康', '张辽'],
    relatedPlaceIds: ['region_youzhou', 'region_jizhou'],
    relatedTags: ['白狼山之战', '卢龙塞', '北方统一', '乌桓'],
    structuralPressure: '幽州边防、乌桓部众与河北残余势力之间仍存在军事和安置压力。',
    contradictionHint: '若乌桓关系、袁氏去向或曹操北方控制已改变，不得照搬白狼山会战及蹋顿、袁氏的固定命运。',
  }),
  historicalEventCard({
    id: 'tk3k_207_longzhong_correction',
    manifestId: 'tk3k_manifest_207_longzhong',
    title: '隆中对与“三顾”史实边界',
    summary: '《三国志·诸葛亮传》记刘备“凡三往，乃见”，会面后形成跨荆益、联孙权并伺机两路北进的战略构想。后世文学把访问过程扩写成完整戏剧场景；史实核心是延揽与战略转向，不是每个拜访细节。',
    relatedNpcNames: ['刘备', '诸葛亮', '徐庶', '关羽', '张飞'],
    relatedPlaceIds: ['region_jingzhou'],
    relatedTags: ['三顾茅庐', '三顾草庐', '三顾茅庐史实核心', '隆中策', '战略转向'],
    structuralPressure: '缺乏稳定根据地的刘备集团仍需回答立足区域、联盟对象与北进路线。',
    contradictionHint: '若刘备与诸葛亮关系、荆益控制或战略目标已改变，只能借鉴战略问题，不得重复“三访草庐”的文学桥段。',
  }),
  historicalEventCard({
    id: 'tk3k_208_changban',
    manifestId: 'tk3k_manifest_208_changban',
    summary: '208 年刘琮降曹后，刘备率部众与大量随行百姓南撤。曹操轻军追至当阳长坂，刘备军失序并与家属、辎重分离，后经汉津与关羽水军会合。张飞断后、赵云救护家属见于个人传记，但不应覆盖人口迁徙主线。',
    relatedNpcNames: ['刘备', '曹操', '刘琮', '关羽', '张飞', '赵云'],
    relatedPlaceIds: ['region_jingzhou'],
    relatedTags: ['当阳长坂', '荆州南撤', '百姓迁徙', '长坂坡纠偏'],
    structuralPressure: '荆州政权交接、军民撤离和江陵军资归属会持续推动南下竞争。',
    contradictionHint: '若刘琮未降、刘备路线或随行人口已改变，不得强制发生长坂溃败；也不能把演义单骑桥段当作完整历史。',
  }),
  historicalEventCard({
    id: 'tk3k_209_jiangling',
    manifestId: 'tk3k_manifest_209_jiangling',
    summary: '赤壁后，周瑜、程普等与据守江陵的曹仁持续争夺南郡，刘备集团也参与截断北道并向荆南扩张。曹仁最终撤出江陵，周瑜领南郡，刘备控制荆南多郡，形成日后孙刘围绕荆州权属的复杂基础。',
    relatedNpcNames: ['周瑜', '程普', '曹仁', '刘备', '关羽', '孙权'],
    relatedPlaceIds: ['region_jingzhou', 'region_yangzhou'],
    relatedTags: ['周瑜攻江陵', '南郡之战', '赤壁战后格局'],
    structuralPressure: '南郡粮道、江防和孙刘双方实际占领线会持续制造荆州权属矛盾。',
    contradictionHint: '若赤壁结果、曹仁驻地或孙刘联盟已改变，不得自动让曹仁撤退、周瑜领南郡或刘备取得荆南。',
  }),
  historicalEventCard({
    id: 'tk3k_211_tong_pass',
    manifestId: 'tk3k_manifest_211_tong_pass',
    summary: '211 年关中诸将因曹操西向军事部署而联合，马超、韩遂等屯潼关。曹操渡河、转入渭南，并利用联盟内部猜疑分化对手，最终击败关中联军；战后马超、韩遂等仍在凉州一带继续活动。',
    relatedNpcNames: ['曹操', '马超', '韩遂', '贾诩', '许褚', '曹仁'],
    relatedPlaceIds: ['region_sili', 'region_liangzhou'],
    relatedTags: ['关中之战', '曹操战马超韩遂', '潼关', '渭南'],
    structuralPressure: '关中军事通道、凉州诸将自治和曹操西线整合之间仍有冲突。',
    contradictionHint: '若关中诸将关系、马超韩遂归属或潼关控制已改变，不得照搬离间过程和曹军胜负。',
  }),
  historicalEventCard({
    id: 'tk3k_215_hefei',
    manifestId: 'tk3k_manifest_215_hefei_jingzhou',
    title: '215 年合肥与逍遥津',
    summary: '215 年孙权率军围合肥，张辽、李典、乐进守城。张辽主动出击挫其前锋；吴军撤退时，张辽又在逍遥津追击孙权近卫。战果数字在叙事中常被夸张，核心是守军主动战术与吴军退却风险。',
    relatedNpcNames: ['孙权', '张辽', '李典', '乐进', '甘宁', '凌统'],
    relatedPlaceIds: ['region_yangzhou'],
    relatedTags: ['逍遥津之战', '合肥之战', '张辽威震逍遥津'],
    structuralPressure: '合肥作为淮南江北前沿，其守军质量、援军和孙吴北进路线会继续形成反复战事。',
    contradictionHint: '若合肥守军、孙权亲征或双方兵力已改变，不得复制固定突袭与追击，更不得把演义兵力数字当成本局精确值。',
  }),
  historicalEventCard({
    id: 'tk3k_215_jingzhou_partition',
    manifestId: 'tk3k_manifest_215_hefei_jingzhou',
    title: '215 年湘水划界',
    summary: '孙权向刘备索取荆州诸郡未果后，吕蒙进取长沙、零陵、桂阳，刘备亦率军东下。因曹操取得汉中，孙刘转而议和，以湘水等实际控制线分割荆州：东部三郡归孙，南郡、零陵、武陵归刘。',
    relatedNpcNames: ['孙权', '刘备', '吕蒙', '鲁肃', '关羽'],
    relatedPlaceIds: ['region_jingzhou', 'region_yangzhou', 'region_yizhou'],
    relatedTags: ['湘水划界', '孙刘荆州分割', '吕蒙取三郡'],
    structuralPressure: '孙刘对荆州借地、占领与盟约的不同理解，以及汉中外压，会迫使双方重新划分资源和防线。',
    contradictionHint: '若孙刘控制线、联盟或曹操汉中局势已改变，不得强制按湘水及史实三郡清单划界。',
  }),
  historicalEventCard({
    id: 'tk3k_219_hanzhong_stages',
    manifestId: 'tk3k_manifest_219_hanzhong',
    title: '217—219 年汉中争夺全阶段',
    summary: '刘备集团自 217 年起争夺汉中，经历阳平关相持、武都方向失利与定军山争夺。219 年黄忠部斩夏侯渊后，曹操亲至仍未能扭转粮运和险要劣势，遂撤出汉中；刘备随后进位汉中王。',
    relatedNpcNames: ['刘备', '曹操', '法正', '黄忠', '夏侯渊', '张郃', '赵颙'],
    relatedPlaceIds: ['region_yizhou', 'region_liangzhou'],
    relatedTags: ['汉中完整阶段', '阳平关', '定军山', '汉中王'],
    structuralPressure: '汉中险要、巴蜀门户、粮运和驻军统帅更替会持续决定蜀魏边界。',
    contradictionHint: '若张鲁降曹、夏侯渊命运、刘备进军或汉中控制已改变，不得把定军山一战直接写成固定胜负与称王结果。',
  }),
  historicalEventCard({
    id: 'tk3k_219_fancheng_jingzhou_chain',
    manifestId: 'tk3k_manifest_219_fancheng_jingzhou',
    title: '219 年樊城—荆州易手完整链',
    summary: '关羽围樊城、襄阳，汉水暴涨使于禁七军覆没，庞德被杀；但其后方与孙吴关系恶化。吕蒙袭取公安、江陵，徐晃解樊城之围，关羽退路与兵源崩溃，最终在临沮附近被擒杀，荆州格局随之改写。',
    relatedNpcNames: ['关羽', '曹仁', '于禁', '庞德', '孙权', '吕蒙', '徐晃', '糜芳', '士仁'],
    relatedPlaceIds: ['region_jingzhou', 'region_yangzhou'],
    relatedTags: ['水淹七军', '白衣渡江', '败走麦城', '荆州易手'],
    structuralPressure: '樊城前线、江陵后方、孙刘互信和沿江补给会共同决定荆州战局，不能只看单场胜败。',
    contradictionHint: '若关羽、于禁、吕蒙等命运或荆州控制线已改变，不得强制水攻、偷袭和关羽败亡，更不能换名复刻完整链。',
  }),
  historicalEventCard({
    id: 'tk3k_221_shu_emperor',
    manifestId: 'tk3k_manifest_221_shu_emperor',
    summary: '曹丕代汉后，刘备于 221 年在成都称帝，延续汉号。荆州丧失、关羽之死、孙刘联盟破裂与曹魏合法性竞争共同推动东征决策；群臣对先魏还是先吴并非一致，不能只归结为私人复仇。',
    relatedNpcNames: ['刘备', '曹丕', '诸葛亮', '赵云', '法正', '孙权', '关羽'],
    relatedPlaceIds: ['region_yizhou', 'region_jingzhou', 'region_yangzhou'],
    relatedTags: ['蜀汉建立', '章武元年', '伐吴决策'],
    structuralPressure: '蜀汉政权的继统合法性、荆州损失和吴魏关系会迫使成都重新选择大战略。',
    contradictionHint: '若献帝、曹丕代汉、关羽或荆州局势已改变，刘备称帝和东征都必须重新判断，不得按史实自动发生。',
  }),
  historicalEventCard({
    id: 'tk3k_221_zhangfei_death',
    manifestId: 'tk3k_manifest_221_shu_emperor',
    title: '张飞遇害与伐吴军务受挫',
    summary: '221 年伐吴前，张飞奉命率军自阆中会师江州，却被帐下张达、范彊杀害，二人持首投吴。此事削弱蜀军东征部署，也反映张飞长期刑罚部下过重所积累的内部风险。',
    relatedNpcNames: ['张飞', '刘备', '张达', '范彊', '孙权'],
    relatedPlaceIds: ['region_yizhou', 'region_jingzhou'],
    relatedTags: ['张飞遇害', '阆中', '伐吴前局势'],
    structuralPressure: '大战前的军纪、将领与亲兵关系以及统帅替补会直接影响东征准备。',
    contradictionHint: '若张飞军纪、亲兵关系、驻地或东征安排已改变，不得强制由张达范彊行刺或投吴。',
  }),
  historicalEventCard({
    id: 'tk3k_225_nanzhong_correction',
    manifestId: 'tk3k_manifest_225_nanzhong',
    title: '南中平定与“七擒孟获”边界',
    summary: '蜀汉在刘备死后处理南中反叛，诸葛亮 225 年南征并恢复当地统治。孟获与“七擒七纵”的完整故事不见于陈寿《三国志》诸葛亮本传，后出材料和演义使其定型；史实核心是军事平定与地方豪帅整合。',
    relatedNpcNames: ['诸葛亮', '孟获', '雍闿', '高定', '朱褒'],
    relatedPlaceIds: ['region_yizhou'],
    relatedTags: ['七擒孟获', '七擒七纵', '七擒孟获纠偏', '南中豪帅', '攻心为上'],
    structuralPressure: '成都对南中交通、豪帅、赋税、兵源与地方自治的协调压力仍会存在。',
    contradictionHint: '若南中未叛、豪帅关系或诸葛亮行程已改变，不得强制七擒七纵；即使出现孟获，也不能把演义次数当作确定事实。',
  }),
  historicalEventCard({
    id: 'tk3k_226_caopi_death',
    manifestId: 'tk3k_manifest_226_caopi_death',
    summary: '226 年魏文帝曹丕病逝，太子曹叡即位。曹真、陈群、司马懿、曹休等受遗命辅政；新君随即面对吴蜀边防、宗室与重臣权力平衡，曹魏完成第二次皇位交接但并非自动稳定。',
    relatedNpcNames: ['曹丕', '曹叡', '曹真', '陈群', '司马懿', '曹休'],
    relatedPlaceIds: ['region_sili', 'region_yangzhou', 'region_jingzhou'],
    relatedTags: ['魏明帝即位', '曹魏皇位交接', '辅政重臣'],
    structuralPressure: '幼弱或新即位君主与宗室、军方、文臣之间的辅政权力仍需重新平衡。',
    contradictionHint: '若曹丕、曹叡继承资格或辅政人选已改变，不得照搬死亡年份、继位者与四人辅政名单。',
  }),
  historicalEventCard({
    id: 'tk3k_228_chencang',
    manifestId: 'tk3k_manifest_228_chencang',
    summary: '228 年冬，诸葛亮由散关攻陈仓。守将郝昭以少量守军依城拒守，针对云梯、冲车、井阑和地道连续反制；二十余日后魏援将至、蜀军粮运受限，诸葛亮撤退。此役体现坚城与后勤，而非单纯武将强弱。',
    relatedNpcNames: ['诸葛亮', '郝昭', '曹真', '王双'],
    relatedPlaceIds: ['region_sili', 'region_liangzhou', 'region_yizhou'],
    relatedTags: ['第二次北伐', '围攻陈仓', '郝昭守陈仓'],
    structuralPressure: '陈仓坚城、散关通道、攻城器械与蜀军远程粮运会继续限制关中北伐。',
    contradictionHint: '若陈仓守将、城防、北伐路线或魏援已改变，不得强制二十余日退兵或复刻攻守器械顺序。',
  }),
  historicalEventCard({
    id: 'tk3k_228_shiting',
    manifestId: 'tk3k_manifest_228_shiting',
    summary: '228 年周鲂以伪降诱曹休深入皖地，孙权任陆逊统军，朱桓、全琮为左右翼，在石亭击破魏军。曹休退路一度受威胁，贾逵及时进军接应。此役是魏吴东线的大规模情报与机动作战。',
    relatedNpcNames: ['周鲂', '曹休', '孙权', '陆逊', '朱桓', '全琮', '贾逵'],
    relatedPlaceIds: ['region_yangzhou'],
    relatedTags: ['石亭大捷', '曹休伐吴', '周鲂诈降'],
    structuralPressure: '淮南前线的诈降情报、湖江地形和援军协同会持续影响魏吴东线。',
    contradictionHint: '若周鲂归属、曹休指挥权或皖地控制已改变，不得强制诈降成功和石亭败局。',
  }),
  historicalEventCard({
    id: 'tk3k_229_wudu_yinping',
    manifestId: 'tk3k_manifest_229_wudu_yinping',
    title: '229 年武都、阴平归蜀',
    summary: '229 年诸葛亮遣陈式攻武都、阴平，魏将郭淮率军应对；诸葛亮进至建威牵制，郭淮退走，两郡遂归蜀汉。这次行动扩大蜀在陇南的前沿，但当地控制仍受道路、羌氐关系和后勤制约。',
    relatedNpcNames: ['诸葛亮', '陈式', '郭淮'],
    relatedPlaceIds: ['region_liangzhou', 'region_yizhou'],
    relatedTags: ['第三次北伐', '武都', '阴平', '陇南前沿'],
    structuralPressure: '陇南郡县、羌氐关系与汉中粮道会继续决定蜀魏西线边界。',
    contradictionHint: '若陈式、郭淮、武都阴平控制或蜀军路线已改变，不得自动把两郡划归蜀汉。',
  }),
  historicalEventCard({
    id: 'tk3k_229_sunquan_emperor',
    manifestId: 'tk3k_manifest_229_wudu_yinping',
    title: '229 年孙权称帝与吴蜀复盟',
    summary: '229 年孙权在武昌称帝，建立吴国皇帝名号，后与蜀汉互遣使者确认联盟和对魏立场。称帝改变三国合法性结构，但并未消除荆州旧怨、边界和各自战略利益。',
    relatedNpcNames: ['孙权', '刘禅', '诸葛亮', '陈震'],
    relatedPlaceIds: ['region_yangzhou', 'region_jingzhou', 'region_yizhou'],
    relatedTags: ['孙权称帝', '吴国建立', '吴蜀复盟'],
    structuralPressure: '吴国名号、蜀吴互认与共同抗魏需求仍会受到边界和战略利益牵制。',
    contradictionHint: '若孙权地位、吴蜀关系或曹魏格局已改变，不得强制称帝、互认或按史实恢复联盟。',
  }),
  historicalEventCard({
    id: 'tk3k_231_qishan_logistics',
    manifestId: 'tk3k_manifest_231_qishan',
    title: '231 年祁山相持、粮运与退兵',
    summary: '231 年诸葛亮再出祁山，与司马懿、张郃等在陇右相持。蜀军虽有局部战果，最终因李严督运失职、粮运不继而退；张郃追击至木门道中箭身亡。战役核心之一是补给与统帅协调。',
    relatedNpcNames: ['诸葛亮', '司马懿', '张郃', '李严', '王平', '魏延'],
    relatedPlaceIds: ['region_liangzhou', 'region_yizhou'],
    relatedTags: ['第四次北伐', '卤城之战', '木门道', '李严运粮'],
    structuralPressure: '陇右攻守、汉中远程粮运和蜀汉内部督运责任会继续限制北伐持续时间。',
    contradictionHint: '若李严职权、张郃命运、粮运或双方部署已改变，不得强制因同一理由退兵或安排木门道死亡。',
  }),
  historicalEventCard({
    id: 'tk3k_234_wuzhangyuan_correction',
    manifestId: 'tk3k_manifest_234_wuzhangyuan',
    title: '五丈原退军与“死诸葛”边界',
    summary: '234 年诸葛亮出斜谷屯五丈原，与司马懿长期相持并尝试屯田，最终病逝军中，蜀军有序撤退，随后发生魏延、杨仪冲突。“死诸葛走生仲达”源于后出记载并经文学强化，不应强制生成木像惊退等固定场面。',
    relatedNpcNames: ['诸葛亮', '司马懿', '魏延', '杨仪', '姜维', '蒋琬', '费祎'],
    relatedPlaceIds: ['region_sili', 'region_liangzhou', 'region_yizhou'],
    relatedTags: ['第五次北伐', '秋风五丈原', '死诸葛走生仲达纠偏', '屯田'],
    structuralPressure: '蜀军统帅继承、撤军秩序与北伐战略延续会在诸葛亮退出后集中爆发。',
    contradictionHint: '若诸葛亮生死、司马懿部署或蜀军继承关系已改变，不得强制病逝、撤军、魏延杨仪冲突或木像惊敌。',
  }),
];
