import type { HistoricalEventApplicability } from '../../engine/types';

export type KnowledgeCoverageStatus = 'covered' | 'partial' | 'missing' | 'correctionNeeded';

export interface ThreeKingdomsMajorEventManifestEntry {
  id: string;
  title: string;
  aliases: string[];
  historicalWindow: HistoricalEventApplicability['historicalWindow'];
  priority: 'P1' | 'P2';
  classification: 'military' | 'political' | 'succession' | 'institutional' | 'correction';
  coverageStatus: KnowledgeCoverageStatus;
  currentCardIds: string[];
  sourceClass: 'historicalCore' | 'historicalDisputed' | 'romanceCorrection';
  divergencePolicy: HistoricalEventApplicability['divergencePolicy'];
  note: string;
}

const STANDARD_DIVERGENCE_POLICY: HistoricalEventApplicability['divergencePolicy'] = {
  mayDelay: true,
  mayTransform: true,
  suppressWhenContradicted: true,
};

const FIXED_RESULT_POLICY: HistoricalEventApplicability['divergencePolicy'] = {
  mayDelay: false,
  mayTransform: false,
  suppressWhenContradicted: true,
};

function event(
  entry: Omit<ThreeKingdomsMajorEventManifestEntry, 'divergencePolicy'> & {
    divergencePolicy?: HistoricalEventApplicability['divergencePolicy'];
  },
): ThreeKingdomsMajorEventManifestEntry {
  return {
    ...entry,
    divergencePolicy: entry.divergencePolicy ?? STANDARD_DIVERGENCE_POLICY,
  };
}

/**
 * 184—280 年重大历史骨架清单。
 *
 * 本表只记录资料覆盖情况，不会自动触发事件。`missing/partial` 项会在后续
 * KnowledgeBase 内容批次补卡；卡片真正进入投影后仍须遵守本局事实最高。
 */
export const THREE_KINGDOMS_MAJOR_EVENT_MANIFEST: ThreeKingdomsMajorEventManifestEntry[] = [
  event({
    id: 'tk3k_manifest_184_yellow_turban',
    title: '黄巾起义',
    aliases: ['黄巾之乱', '太平道起事'],
    historicalWindow: { earliest: '公元184年', typical: '公元184年', latest: '公元185年', afterlifeUntil: '公元190年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_yellow_turban_184', 'tk3k_yellow_turban_aftermath'],
    sourceClass: 'historicalCore',
    note: '起事本身与黄巾余波已有独立锚点。',
  }),
  event({
    id: 'tk3k_manifest_189_luoyang_coup',
    title: '洛阳政变与董卓入京',
    aliases: ['何进诛宦官', '董卓进京', '废少立献'],
    historicalWindow: { earliest: '公元189年', typical: '公元189年', latest: '公元190年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_189_luoyang_coup', 'tk3k_dongzhuo_enters_capital', 'tk3k_189_abdication'],
    sourceClass: 'historicalCore',
    note: '已有完整的宫廷冲突、入京与废立链。',
  }),
  event({
    id: 'tk3k_manifest_190_coalition',
    title: '关东联军与迁都长安',
    aliases: ['讨董联军', '十八路诸侯', '迁都长安', '三英战吕布', '温酒斩华雄'],
    historicalWindow: { earliest: '公元190年', typical: '公元190年', latest: '公元191年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_190_coalition_formed', 'tk3k_coalition_disunity', 'tk3k_dongzhuo_moves_capital'],
    sourceClass: 'historicalCore',
    note: '联军松散性与迁都后果均有锚点。',
  }),
  event({
    id: 'tk3k_manifest_192_dongzhuo_death',
    title: '董卓被诛与长安权力真空',
    aliases: ['王允诛董卓', '吕布刺董卓'],
    historicalWindow: { earliest: '公元192年', typical: '公元192年', latest: '公元193年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_192_dongzhuo_death'],
    sourceClass: 'historicalCore',
    note: '人物早期卡不能替代事件及其政治后果。',
  }),
  event({
    id: 'tk3k_manifest_192_lijue_guosi_changan',
    title: '李傕郭汜攻入长安',
    aliases: ['李郭之乱', '长安之乱'],
    historicalWindow: { earliest: '公元192年', typical: '公元192年', latest: '公元195年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_192_lijue_guosi_changan'],
    sourceClass: 'historicalCore',
    note: '需要覆盖献帝再度受制与关中秩序崩坏。',
  }),
  event({
    id: 'tk3k_manifest_193_xuzhou_campaign',
    title: '曹操征徐州',
    aliases: ['徐州之战', '曹操伐陶谦'],
    historicalWindow: { earliest: '公元193年', typical: '公元193年', latest: '公元194年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_193_xuzhou_campaign'],
    sourceClass: 'historicalCore',
    note: '需同时覆盖战争、屠戮争议与地方人口后果。',
  }),
  event({
    id: 'tk3k_manifest_194_xuzhou_succession',
    title: '陶谦死后徐州权力交接',
    aliases: ['刘备领徐州', '三让徐州'],
    historicalWindow: { earliest: '公元194年', typical: '公元194年', latest: '公元195年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_194_xuzhou_succession'],
    sourceClass: 'romanceCorrection',
    note: '补史实核心，并区分“三让”的文学组织。',
  }),
  event({
    id: 'tk3k_manifest_194_yanzhou_war',
    title: '吕布入兖州与兖州争夺',
    aliases: ['曹吕兖州之战', '吕布袭兖州'],
    historicalWindow: { earliest: '公元194年', typical: '公元194年', latest: '公元195年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_194_yanzhou_war'],
    sourceClass: 'historicalCore',
    note: '当前只有早期人物与地域卡。',
  }),
  event({
    id: 'tk3k_manifest_195_emperor_east_return',
    title: '献帝东归',
    aliases: ['献帝东归洛阳', '天子东归'],
    historicalWindow: { earliest: '公元195年', typical: '公元195年', latest: '公元196年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_195_emperor_east_return', 'tk3k_196_emperor_xuchang'],
    sourceClass: 'historicalCore',
    note: '已有奉迎结果，缺东归过程与洛阳困局。',
  }),
  event({
    id: 'tk3k_manifest_196_emperor_xuchang',
    title: '曹操奉迎天子迁许',
    aliases: ['奉天子以令不臣', '挟天子以令诸侯', '迁都许县'],
    historicalWindow: { earliest: '公元196年', typical: '公元196年', latest: '公元197年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_196_emperor_xuchang', 'tk3k_place_xuchang'],
    sourceClass: 'historicalCore',
    note: '注意区分史书措辞与后世概括。',
  }),
  event({
    id: 'tk3k_manifest_197_yuanshu_emperor',
    title: '袁术称帝',
    aliases: ['袁术僭号', '仲氏政权'],
    historicalWindow: { earliest: '公元197年', typical: '公元197年', latest: '公元198年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_197_yuanshu_emperor'],
    sourceClass: 'historicalCore',
    note: '必须允许本局因袁术处境变化而不发生或变形。',
  }),
  event({
    id: 'tk3k_manifest_197_wancheng',
    title: '宛城之战',
    aliases: ['曹操征张绣', '淯水之战'],
    historicalWindow: { earliest: '公元197年', typical: '公元197年', latest: '公元199年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_197_wancheng'],
    sourceClass: 'historicalCore',
    note: '需要覆盖张绣、贾诩与曹操集团损失。',
  }),
  event({
    id: 'tk3k_manifest_198_xiapi',
    title: '下邳之战与吕布败亡',
    aliases: ['曹操擒吕布', '白门楼'],
    historicalWindow: { earliest: '公元198年', typical: '公元198年', latest: '公元199年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_198_xiapi'],
    sourceClass: 'historicalCore',
    note: '白门楼叙事需要史实/演义边界。',
  }),
  event({
    id: 'tk3k_manifest_199_yijing',
    title: '易京之战与公孙瓒败亡',
    aliases: ['袁绍灭公孙瓒', '易京楼陷落'],
    historicalWindow: { earliest: '公元199年', typical: '公元199年', latest: '公元200年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_199_yijing'],
    sourceClass: 'historicalCore',
    note: '用于补齐河北格局变化。',
  }),
  event({
    id: 'tk3k_manifest_200_guandu',
    title: '官渡之战',
    aliases: ['白马之战', '延津之战', '乌巢之战', '官渡决战'],
    historicalWindow: { earliest: '公元199年', typical: '公元200年', latest: '公元201年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk_guandu_not_early_fixed', 'tk3k_200_guandu_standoff', 'tk3k_200_guandu_campaign'],
    sourceClass: 'historicalCore',
    note: '已有对峙与非固定结局边界，缺完整战役序列。',
  }),
  event({
    id: 'tk3k_manifest_202_yuan_succession',
    title: '袁绍死后继承战争',
    aliases: ['袁谭袁尚之争', '河北继承战争'],
    historicalWindow: { earliest: '公元202年', typical: '公元202年', latest: '公元207年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_202_yuan_succession'],
    sourceClass: 'historicalCore',
    note: '需覆盖曹操平定河北的阶段条件。',
  }),
  event({
    id: 'tk3k_manifest_207_wuhuan',
    title: '北征乌桓',
    aliases: ['白狼山之战', '曹操北征乌桓'],
    historicalWindow: { earliest: '公元206年', typical: '公元207年', latest: '公元208年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_207_wuhuan'],
    sourceClass: 'historicalCore',
    note: '补北方统一与边疆关系。',
  }),
  event({
    id: 'tk3k_manifest_207_longzhong',
    title: '隆中对与刘备集团战略转向',
    aliases: ['三顾茅庐', '隆中策'],
    historicalWindow: { earliest: '公元207年', typical: '公元207年', latest: '公元208年' },
    priority: 'P2',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_207_longzhong_plan', 'tk3k_zhugeliang_207_214', 'tk3k_207_longzhong_correction'],
    sourceClass: 'historicalDisputed',
    note: '战略核心已有，需补三顾文学组织边界。',
  }),
  event({
    id: 'tk3k_manifest_208_changban',
    title: '长坂与荆州南下',
    aliases: ['长坂坡', '当阳长坂'],
    historicalWindow: { earliest: '公元208年', typical: '公元208年', latest: '公元209年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_208_changban'],
    sourceClass: 'historicalCore',
    note: '需区分撤退、人口迁徙与演义单骑叙事。',
  }),
  event({
    id: 'tk3k_manifest_208_chibi',
    title: '赤壁之战',
    aliases: ['赤壁大战', '乌林之战', '草船借箭', '借东风', '华容道'],
    historicalWindow: { earliest: '公元208年', typical: '公元208年', latest: '公元209年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_208_chibi_approach', 'tk3k_zhouyu_chibi'],
    sourceClass: 'historicalCore',
    note: '后续补草船借箭、借东风、华容道纠偏。',
  }),
  event({
    id: 'tk3k_manifest_209_jiangling',
    title: '江陵与南郡争夺',
    aliases: ['南郡之战', '周瑜攻江陵'],
    historicalWindow: { earliest: '公元208年', typical: '公元209年', latest: '公元210年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_209_jiangling'],
    sourceClass: 'historicalCore',
    note: '赤壁之后荆州格局的关键缺口。',
  }),
  event({
    id: 'tk3k_manifest_211_tong_pass',
    title: '潼关之战',
    aliases: ['关中之战', '曹操战马超韩遂'],
    historicalWindow: { earliest: '公元211年', typical: '公元211年', latest: '公元212年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_211_tong_pass'],
    sourceClass: 'historicalCore',
    note: '补齐关中与凉州集团变化。',
  }),
  event({
    id: 'tk3k_manifest_214_yizhou',
    title: '刘备取得益州',
    aliases: ['刘备入蜀', '成都开城'],
    historicalWindow: { earliest: '公元211年', typical: '公元214年', latest: '公元215年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_211_rushu_prelude', 'tk3k_214_yizhou_transition'],
    sourceClass: 'historicalCore',
    note: '已有入蜀前夜、人物与益州易主锚点。',
  }),
  event({
    id: 'tk3k_manifest_215_hefei_jingzhou',
    title: '合肥战事与孙刘荆州分割',
    aliases: ['逍遥津之战', '湘水划界', '单刀赴会'],
    historicalWindow: { earliest: '公元215年', typical: '公元215年', latest: '公元216年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_zhangliao', 'tk3k_215_hefei', 'tk3k_215_jingzhou_partition'],
    sourceClass: 'historicalCore',
    note: '人物卡提及合肥，但缺双线格局事件卡。',
  }),
  event({
    id: 'tk3k_manifest_219_hanzhong',
    title: '汉中争夺',
    aliases: ['定军山之战', '刘备进位汉中王'],
    historicalWindow: { earliest: '公元217年', typical: '公元219年', latest: '公元220年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_219_hanzhong_campaign', 'tk3k_xiahouyuan', 'tk3k_219_hanzhong_stages'],
    sourceClass: 'historicalCore',
    note: '已有结果锚点，需补完整阶段。',
  }),
  event({
    id: 'tk3k_manifest_219_fancheng_jingzhou',
    title: '樊城之战与荆州易手',
    aliases: ['水淹七军', '吕蒙白衣渡江', '关羽败走麦城'],
    historicalWindow: { earliest: '公元219年', typical: '公元219年', latest: '公元220年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_guanyu_jingzhou_guard', 'tk3k_lvmeng_jingzhou_capture', 'tk3k_219_fancheng_jingzhou_chain'],
    sourceClass: 'historicalCore',
    note: '荆州易手已有，缺樊城与关羽终局完整链。',
  }),
  event({
    id: 'tk3k_manifest_220_wei',
    title: '曹丕代汉建魏',
    aliases: ['魏代汉', '曹魏建立'],
    historicalWindow: { earliest: '公元220年', typical: '公元220年', latest: '公元221年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_220_caopi_usurp', 'tk3k_caopi_220'],
    sourceClass: 'historicalCore',
    note: '已有政治与人物阶段锚点。',
  }),
  event({
    id: 'tk3k_manifest_221_shu_emperor',
    title: '刘备称帝与伐吴前局势',
    aliases: ['蜀汉建立', '刘备称帝'],
    historicalWindow: { earliest: '公元221年', typical: '公元221年', latest: '公元222年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_221_shu_emperor', 'tk3k_221_zhangfei_death'],
    sourceClass: 'historicalCore',
    note: '需与张飞遇害及伐吴决策分层。',
  }),
  event({
    id: 'tk3k_manifest_222_yiling',
    title: '夷陵之战',
    aliases: ['猇亭之战', '夷陵火攻', '火烧连营'],
    historicalWindow: { earliest: '公元221年', typical: '公元222年', latest: '公元223年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_222_yiling_defeat', 'tk3k_luxun_yiling'],
    sourceClass: 'historicalCore',
    note: '历史核心已有，补别名和演义夸饰说明即可。',
  }),
  event({
    id: 'tk3k_manifest_223_baidi',
    title: '白帝托孤',
    aliases: ['永安托孤', '刘备托孤'],
    historicalWindow: { earliest: '公元223年', typical: '公元223年', latest: '公元224年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_223_baidi_entrust'],
    sourceClass: 'historicalCore',
    note: '本局若刘备未败亡，不得强制托孤。',
  }),
  event({
    id: 'tk3k_manifest_225_nanzhong',
    title: '诸葛亮南征',
    aliases: ['南中平定', '七擒孟获'],
    historicalWindow: { earliest: '公元225年', typical: '公元225年', latest: '公元226年' },
    priority: 'P2',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_225_nanzhong_pacification', 'tk3k_menghuo_nanzhong', 'tk3k_225_nanzhong_correction'],
    sourceClass: 'romanceCorrection',
    note: '历史南征已有，需补“七擒”文献边界。',
  }),
  event({
    id: 'tk3k_manifest_226_caopi_death',
    title: '曹丕去世与曹叡继位',
    aliases: ['魏明帝即位'],
    historicalWindow: { earliest: '公元226年', typical: '公元226年', latest: '公元227年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_226_caopi_death'],
    sourceClass: 'historicalCore',
    note: '补曹魏第二次皇位交接。',
  }),
  event({
    id: 'tk3k_manifest_228_first_northern',
    title: '第一次北伐与街亭之失',
    aliases: ['初出祁山', '街亭之战'],
    historicalWindow: { earliest: '公元227年', typical: '公元228年', latest: '公元229年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_228_first_northern_expedition', 'tk3k_masu_jieting'],
    sourceClass: 'historicalCore',
    note: '已有完整核心锚点。',
  }),
  event({
    id: 'tk3k_manifest_228_chencang',
    title: '陈仓之战',
    aliases: ['第二次北伐', '围攻陈仓'],
    historicalWindow: { earliest: '公元228年', typical: '公元228年', latest: '公元229年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_228_chencang'],
    sourceClass: 'historicalCore',
    note: '六出祁山概括下的重要缺口。',
  }),
  event({
    id: 'tk3k_manifest_228_shiting',
    title: '石亭之战',
    aliases: ['曹休伐吴', '石亭大捷'],
    historicalWindow: { earliest: '公元228年', typical: '公元228年', latest: '公元229年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_228_shiting'],
    sourceClass: 'historicalCore',
    note: '补东线魏吴战争。',
  }),
  event({
    id: 'tk3k_manifest_229_wudu_yinping',
    title: '武都阴平归蜀与吴称帝',
    aliases: ['第三次北伐', '孙权称帝', '吴蜀复盟'],
    historicalWindow: { earliest: '公元229年', typical: '公元229年', latest: '公元230年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_229_wushu_realliance', 'tk3k_229_wudu_yinping', 'tk3k_229_sunquan_emperor'],
    sourceClass: 'historicalCore',
    note: '复盟已有，缺武都阴平及吴正式称帝。',
  }),
  event({
    id: 'tk3k_manifest_231_qishan',
    title: '第四次北伐与祁山相持',
    aliases: ['祁山之战', '卤城之战'],
    historicalWindow: { earliest: '公元231年', typical: '公元231年', latest: '公元232年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_231_qishan_stalemate', 'tk3k_231_qishan_logistics'],
    sourceClass: 'historicalCore',
    note: '需补后勤与退兵过程。',
  }),
  event({
    id: 'tk3k_manifest_234_wuzhangyuan',
    title: '五丈原与诸葛亮去世',
    aliases: ['第五次北伐', '秋风五丈原', '死诸葛走生仲达'],
    historicalWindow: { earliest: '公元234年', typical: '公元234年', latest: '公元235年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_234_wuzhangyuan', 'tk3k_jiangwan_feiwei', 'tk3k_234_wuzhangyuan_correction'],
    sourceClass: 'romanceCorrection',
    note: '史实后继已有，需补著名文学名目纠偏。',
  }),
  event({
    id: 'tk3k_manifest_238_liaodong',
    title: '司马懿平辽东',
    aliases: ['襄平之战', '公孙渊败亡'],
    historicalWindow: { earliest: '公元237年', typical: '公元238年', latest: '公元239年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_238_liaodong_campaign'],
    sourceClass: 'historicalCore',
    note: '235—248 空白段的关键节点。',
  }),
  event({
    id: 'tk3k_manifest_239_wei_regency',
    title: '曹叡去世与曹芳摄政格局',
    aliases: ['曹芳即位', '曹爽司马懿辅政'],
    historicalWindow: { earliest: '公元239年', typical: '公元239年', latest: '公元240年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_239_wei_regency'],
    sourceClass: 'historicalCore',
    note: '为高平陵之前置格局。',
  }),
  event({
    id: 'tk3k_manifest_244_xingshi',
    title: '兴势之战',
    aliases: ['曹爽伐蜀', '兴势山之战'],
    historicalWindow: { earliest: '公元244年', typical: '公元244年', latest: '公元245年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_244_xingshi_campaign'],
    sourceClass: 'historicalCore',
    note: '补曹爽军事声望变化。',
  }),
  event({
    id: 'tk3k_manifest_249_gaopingling',
    title: '高平陵之变',
    aliases: ['司马懿政变', '高平陵政变'],
    historicalWindow: { earliest: '公元249年', typical: '公元249年', latest: '公元250年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_249_gaopingling', 'tk3k_simayi_231_249'],
    sourceClass: 'historicalCore',
    note: '已有事件和司马懿阶段卡。',
  }),
  event({
    id: 'tk3k_manifest_251_wangling',
    title: '王凌之变',
    aliases: ['淮南一叛'],
    historicalWindow: { earliest: '公元251年', typical: '公元251年', latest: '公元252年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_251_wangling_revolt'],
    sourceClass: 'historicalCore',
    note: '淮南三叛第一阶段。',
  }),
  event({
    id: 'tk3k_manifest_252_sunquan_death',
    title: '孙权去世与东吴继承危机',
    aliases: ['孙亮即位', '吴大帝崩'],
    historicalWindow: { earliest: '公元252年', typical: '公元252年', latest: '公元253年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_252_sunquan_succession'],
    sourceClass: 'historicalCore',
    note: '当前东吴势力卡止于252年，缺后续政局。',
  }),
  event({
    id: 'tk3k_manifest_253_zhugeke',
    title: '诸葛恪败亡',
    aliases: ['诸葛恪被杀', '东兴之后'],
    historicalWindow: { earliest: '公元253年', typical: '公元253年', latest: '公元254年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_253_zhugeke_fall'],
    sourceClass: 'historicalCore',
    note: '补东吴权臣与继承危机。',
  }),
  event({
    id: 'tk3k_manifest_255_shouchun',
    title: '毌丘俭文钦之乱',
    aliases: ['淮南二叛', '寿春之乱'],
    historicalWindow: { earliest: '公元255年', typical: '公元255年', latest: '公元256年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_255_shouchun_revolt'],
    sourceClass: 'historicalCore',
    note: '与洮西大捷并行，不得被蜀线遮蔽。',
  }),
  event({
    id: 'tk3k_manifest_255_taoxi',
    title: '洮西之战',
    aliases: ['洮西大捷', '狄道之战'],
    historicalWindow: { earliest: '公元255年', typical: '公元255年', latest: '公元256年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_255_taoxi_victory', 'tk3k_jiangwei_253_259'],
    sourceClass: 'historicalCore',
    note: '已有姜维主兵与战果锚点。',
  }),
  event({
    id: 'tk3k_manifest_256_duangu',
    title: '段谷之败',
    aliases: ['段谷之战', '姜维段谷败绩'],
    historicalWindow: { earliest: '公元256年', typical: '公元256年', latest: '公元257年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_256_duangu_defeat'],
    sourceClass: 'historicalCore',
    note: '补北伐代价与蜀汉内部压力。',
  }),
  event({
    id: 'tk3k_manifest_257_zhugedan',
    title: '诸葛诞之乱',
    aliases: ['淮南三叛', '寿春围城'],
    historicalWindow: { earliest: '公元257年', typical: '公元257年', latest: '公元258年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_257_zhugedan_revolt'],
    sourceClass: 'historicalCore',
    note: '补司马氏掌权过程中的最大地方反抗。',
  }),
  event({
    id: 'tk3k_manifest_260_caomao',
    title: '曹髦之死',
    aliases: ['曹髦讨司马昭', '成济弑君'],
    historicalWindow: { earliest: '公元260年', typical: '公元260年', latest: '公元261年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_260_caomao_death'],
    sourceClass: 'historicalCore',
    note: '补曹魏皇权与司马氏关系的终局转折。',
  }),
  event({
    id: 'tk3k_manifest_263_shu_fall',
    title: '魏灭蜀',
    aliases: ['蜀汉灭亡', '邓艾偷渡阴平', '成都投降'],
    historicalWindow: { earliest: '公元263年', typical: '公元263年', latest: '公元264年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_263_shuhan_fall', 'tk3k_dengai_263', 'tk3k_zhonghui_263', 'tk3k_jiangwei_late_263'],
    sourceClass: 'historicalCore',
    note: '三线已有，但后续钟会之乱仍缺。',
  }),
  event({
    id: 'tk3k_manifest_264_zhonghui',
    title: '钟会之乱',
    aliases: ['成都之变', '钟会姜维之变'],
    historicalWindow: { earliest: '公元264年', typical: '公元264年', latest: '公元265年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_264_zhonghui_revolt'],
    sourceClass: 'historicalCore',
    note: '正式280范围的首个空白节点。',
  }),
  event({
    id: 'tk3k_manifest_265_jin',
    title: '司马炎代魏建晋',
    aliases: ['晋代魏', '西晋建立'],
    historicalWindow: { earliest: '公元265年', typical: '公元265年', latest: '公元266年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_265_jin_replaces_wei'],
    sourceClass: 'historicalCore',
    note: '必须明确蜀亡不等于天下统一。',
  }),
  event({
    id: 'tk3k_manifest_269_wu_late',
    title: '孙皓后期政局与晋吴对峙',
    aliases: ['吴末政局', '孙皓统治'],
    historicalWindow: { earliest: '公元264年', typical: '公元269年', latest: '公元279年' },
    priority: 'P1',
    classification: 'political',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_269_late_wu_standoff'],
    sourceClass: 'historicalCore',
    note: '不是单一事件卡，需作为后期吴国阶段锚点。',
  }),
  event({
    id: 'tk3k_manifest_272_xiling',
    title: '西陵之战与晋吴边境',
    aliases: ['陆抗西陵破晋'],
    historicalWindow: { earliest: '公元272年', typical: '公元272年', latest: '公元273年' },
    priority: 'P2',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_272_xiling_campaign'],
    sourceClass: 'historicalCore',
    note: '用于避免后期吴国被写成毫无军事反应。',
  }),
  event({
    id: 'tk3k_manifest_279_jin_campaign',
    title: '晋伐吴',
    aliases: ['六路伐吴', '王濬楼船下益州'],
    historicalWindow: { earliest: '公元279年', typical: '公元279年', latest: '公元280年' },
    priority: 'P1',
    classification: 'military',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_279_jin_conquest_wu'],
    sourceClass: 'historicalCore',
    note: '需覆盖多路推进，而非只写单一名将。',
  }),
  event({
    id: 'tk3k_manifest_280_wu_fall',
    title: '晋灭吴',
    aliases: ['孙皓降晋', '三国归晋'],
    historicalWindow: { earliest: '公元280年', typical: '公元280年', latest: '公元280年' },
    priority: 'P1',
    classification: 'succession',
    coverageStatus: 'covered',
    currentCardIds: ['tk3k_280_wu_fall'],
    sourceClass: 'historicalCore',
    divergencePolicy: FIXED_RESULT_POLICY,
    note: '资料范围终点；本局若吴或晋不存在，必须判为偏转而非换名复演。',
  }),
];
