import type { MapLayerKind, MapNode } from '../../engine/types';

/**
 * 三国地图骨架 - 全国轻量州级节点
 * 第一阶段只做浅切片（豫州颍川附近），其余州只保留骨架
 */
const threeKingdomsMapSeedRaw: MapNode[] = [
  // ===== 全国州级骨架 =====
  {
    id: 'region_sili',
    name: '司隶',
    level: '州',
    summary: '京畿所在，洛阳、长安两都之间，天下中枢。然朝政日非，洛阳城中风云诡谲。',
    connectedRegionIds: ['region_yuzhou', 'region_jizhou', 'region_yanzhou', 'region_jingzhou', 'region_liangzhou', 'region_bingzhou'],
    controlHint: '汉廷名义控制，实际权在宦官外戚',
    tensionHint: '高 - 朝廷内部斗争激烈',
  },
  {
    id: 'region_yuzhou',
    name: '豫州',
    level: '州',
    summary: '中原腹地，颍川、汝南文风鼎盛。四战之地，黄巾军活动频繁，官府与豪族各怀心思。',
    connectedRegionIds: ['region_sili', 'region_yanzhou', 'region_xuzhou', 'region_yangzhou', 'region_jingzhou'],
    controlHint: '名义属汉，实际豪族与黄巾交织',
    tensionHint: '高 - 黄巾活动中心区域之一',
    subLocations: [
      {
        id: 'loc_yingchuan',
        name: '颍川',
        level: '郡',
        summary: '颍川郡治所在，士族云集，荀氏、陈氏、钟氏等大族根基深厚。然黄巾暗流涌动，城外乡里已不安宁。',
        connectedRegionIds: ['loc_runan', 'loc_nanyang', 'region_sili'],
        controlHint: '郡守名义管辖，豪族实际主导',
        tensionHint: '中 - 士族与黄巾暗流并存',
        subLocations: [
          {
            id: 'loc_yingchuan_town',
            name: '颍川郡治',
            level: '县',
            summary: '郡城所在，官署、市集、学馆俱全。士人往来频繁，消息灵通之处。',
            connectedRegionIds: ['loc_yingchuan_market', 'loc_yingchuan_office', 'loc_yingchuan_road'],
            controlHint: '郡守衙门',
            tensionHint: '低 - 城内尚算安定',
          },
          {
            id: 'loc_yingchuan_market',
            name: '市集',
            level: '县',
            summary: '颍川城中最热闹的所在，南北货物汇集。三教九流混杂，打听消息的好去处。',
            connectedRegionIds: ['loc_yingchuan_town', 'loc_yingchuan_village'],
            controlHint: '市令管辖，豪商影响',
            tensionHint: '低',
          },
          {
            id: 'loc_yingchuan_office',
            name: '官署',
            level: '县',
            summary: '郡守衙门所在，门前衙役林立，百姓望而却步。公文往来、赋税征发的中心。',
            connectedRegionIds: ['loc_yingchuan_town'],
            controlHint: '颍川太守',
            tensionHint: '中 - 征发频繁，民怨渐起',
          },
          {
            id: 'loc_yingchuan_road',
            name: '驿道',
            level: '县',
            summary: '连接颍川与外界的官道，商旅往来络绎。然近来时有拦路劫匪，旅人多结伴而行。',
            connectedRegionIds: ['loc_yingchuan_town', 'loc_yingchuan_estate', 'loc_yingchuan_village'],
            controlHint: '无明确控制',
            tensionHint: '中高 - 道路不靖',
          },
          {
            id: 'loc_yingchuan_estate',
            name: '豪族庄园',
            level: '县',
            summary: '城郊大族庄园，高墙深院，私兵巡守。寻常百姓不得擅入，内里却是另一番天地。',
            connectedRegionIds: ['loc_yingchuan_road', 'loc_yingchuan_village'],
            controlHint: '地方豪族',
            tensionHint: '中 - 表面平静，内里暗斗',
          },
          {
            id: 'loc_yingchuan_village',
            name: '村落',
            level: '县',
            summary: '散落在颍川城外的村庄，农夫日出而作日落而息。然近来人心惶惶，黄巾符水已悄然流入。',
            connectedRegionIds: ['loc_yingchuan_market', 'loc_yingchuan_road', 'loc_yingchuan_huangjin_rumor'],
            controlHint: '名义属郡县，实际豪族势力渗入',
            tensionHint: '高 - 黄巾势力暗中渗透',
          },
          {
            id: 'loc_yingchuan_huangjin_rumor',
            name: '黄巾活动传闻区域',
            level: '县',
            summary: '据说太平道在此地暗中传道，符水治病、聚众讲经。官府虽已警觉，但信众日增。',
            connectedRegionIds: ['loc_yingchuan_village'],
            controlHint: '无明确控制（黄巾暗中活动）',
            tensionHint: '高 - 叛乱一触即发',
          },
        ],
      },
      {
        id: 'loc_runan',
        name: '汝南',
        level: '郡',
        summary: '豫州大郡，袁氏家族根基所在。士族势力根深蒂固，地方豪强林立。',
        connectedRegionIds: ['loc_yingchuan', 'loc_nanyang', 'region_yangzhou'],
        controlHint: '袁氏及地方豪族',
        tensionHint: '中 - 豪族互斗',
      },
      {
        id: 'loc_nanyang',
        name: '南阳',
        level: '郡',
        summary: '荆州北部重镇，帝乡所在。商业繁华，人口稠密，是南北交通要冲。',
        connectedRegionIds: ['loc_yingchuan', 'loc_runan', 'region_jingzhou', 'region_sili'],
        controlHint: '荆州牧管辖',
        tensionHint: '中 - 地理位置重要，各方关注',
      },
    ],
  },
  {
    id: 'region_jizhou',
    name: '冀州',
    level: '州',
    summary: '河北重镇，地广民多。太平道大本营巨鹿所在，黄巾起义的策源地。',
    connectedRegionIds: ['region_sili', 'region_yanzhou', 'region_qingzhou', 'region_bingzhou', 'region_youzhou'],
    controlHint: '名属汉廷，黄巾势力深厚',
    tensionHint: '极高 - 黄巾起义策源地',
  },
  {
    id: 'region_yanzhou',
    name: '兖州',
    level: '州',
    summary: '中原要冲，连接东西南北。受黄巾影响严重，社会秩序动荡。',
    connectedRegionIds: ['region_sili', 'region_yuzhou', 'region_xuzhou', 'region_qingzhou', 'region_jizhou'],
    controlHint: '汉廷与地方势力博弈',
    tensionHint: '高 - 黄巾蔓延',
  },
  {
    id: 'region_jingzhou',
    name: '荆州',
    level: '州',
    summary: '南方大州，地跨长江。物产丰饶，人口众多，在乱世中相对安定。',
    connectedRegionIds: ['region_sili', 'region_yuzhou', 'region_yangzhou', 'region_yizhou'],
    controlHint: '荆州牧管辖，相对稳定',
    tensionHint: '低中 - 相对安定',
  },
  {
    id: 'region_yangzhou',
    name: '扬州',
    level: '州',
    summary: '江东之地，物阜民丰。远离中原战火，但山越时有骚动。',
    connectedRegionIds: ['region_yuzhou', 'region_xuzhou', 'region_jingzhou'],
    controlHint: '扬州牧管辖',
    tensionHint: '低 - 偏远安定',
  },
  {
    id: 'region_yizhou',
    name: '益州',
    level: '州',
    summary: '天府之国，崇山峻岭中藏着富饶盆地。远离中原纷争，然道路艰险。',
    connectedRegionIds: ['region_jingzhou', 'region_liangzhou'],
    controlHint: '益州牧管辖',
    tensionHint: '低 - 偏安一隅',
  },
  {
    id: 'region_liangzhou',
    name: '凉州',
    level: '州',
    summary: '西北边陲，羌汉杂处。边军骁勇，然朝廷控制力薄弱，叛乱频发。',
    connectedRegionIds: ['region_sili', 'region_yizhou', 'region_bingzhou'],
    controlHint: '凉州牧及边军将领',
    tensionHint: '高 - 羌乱不断',
  },
  {
    id: 'region_youzhou',
    name: '幽州',
    level: '州',
    summary: '东北边疆，抵御鲜卑乌桓的前线。边军精锐，民风彪悍。',
    connectedRegionIds: ['region_jizhou', 'region_bingzhou', 'region_qingzhou'],
    controlHint: '幽州牧管辖',
    tensionHint: '中 - 外患不断',
  },
  {
    id: 'region_bingzhou',
    name: '并州',
    level: '州',
    summary: '北方边州，匈奴鲜卑环伺。吕布、张辽等名将出身于此。',
    connectedRegionIds: ['region_sili', 'region_jizhou', 'region_youzhou', 'region_liangzhou'],
    controlHint: '并州牧管辖',
    tensionHint: '中高 - 边患频繁',
  },
  {
    id: 'region_xuzhou',
    name: '徐州',
    level: '州',
    summary: '东海之滨，富庶之地。然近接中原，战火随时可能蔓延至此。',
    connectedRegionIds: ['region_yuzhou', 'region_yanzhou', 'region_qingzhou', 'region_yangzhou'],
    controlHint: '徐州牧管辖',
    tensionHint: '中 - 四面受敌',
  },
  {
    id: 'region_qingzhou',
    name: '青州',
    level: '州',
    summary: '齐鲁故地，东临大海。黄巾军在此声势浩大，州郡残破。',
    connectedRegionIds: ['region_jizhou', 'region_yanzhou', 'region_xuzhou', 'region_youzhou'],
    controlHint: '黄巾势力极盛',
    tensionHint: '极高 - 黄巾重灾区',
  },
  {
    id: 'region_jiaozhou',
    name: '交州',
    level: '州',
    summary: '岭南偏远之地，远离中原纷争。炎瘴之地，开发程度低。',
    connectedRegionIds: ['region_yangzhou', 'region_jingzhou', 'region_yizhou'],
    controlHint: '交州牧管辖',
    tensionHint: '低 - 地处偏远',
  },
];

const mapSeedLayerByDepth = (depth: number): MapLayerKind => {
  if (depth <= 1) return 'region';
  if (depth === 2) return 'place';
  return 'scene';
};

const withMapSeedLayers = (node: MapNode, depth: number): MapNode => ({
  ...node,
  mapLayer: node.mapLayer ?? mapSeedLayerByDepth(depth),
  subLocations: node.subLocations?.map((child) => withMapSeedLayers(child, depth + 1)),
});

export const threeKingdomsMapSeed: MapNode[] = threeKingdomsMapSeedRaw.map((node) => withMapSeedLayers(node, 0));
