import type { StartBookmark } from '../../engine/types';

/**
 * 三国开局书签
 * 第一阶段提供一组可验收的三国开局剧本。
 */
export const threeKingdomsStartBookmarks: StartBookmark[] = [
  {
    id: 'bookmark_184_yellow_turban',
    label: '184 黄巾初起',
    startDate: '184年3月',
    relatedTimelineAnchorIds: ['anchor_184_yellow_turban'],
    description: '黄巾乱起，天下震动。你身处乱世序幕之中，是趁乱而起，还是自保求生？一切尚未定局。',
    recommendedRegions: ['loc_yingchuan', 'loc_runan', 'loc_nanyang'],
    recommendedOrigins: ['寒门士子', '县中小吏', '流民', '黄巾信众'],
    situationSummary: '公元184年春，太平道张角起事，黄巾军遍及八州。朝廷急召各地募兵平乱，然州郡各自为政，豪族各怀心思。豫州颍川一带，太平道暗中传道已久，民心动荡，官府警觉但无力控制。你正身处这山雨欲来的乱世风口。',
  },
  {
    id: 'bookmark_189_luoyang_storm',
    label: '189 洛阳风暴',
    startDate: '189年9月',
    relatedTimelineAnchorIds: ['anchor_189_dong_zhuo'],
    description: '灵帝崩逝，何进被杀，董卓入京。洛阳一夜之间换了天，朝堂、军营、士人、宦官残党都在寻找退路。',
    recommendedRegions: ['region_sili', 'region_yuzhou', 'loc_yingchuan'],
    recommendedOrigins: ['寒门士子', '县中小吏', '游侠', '豪族旁支'],
    situationSummary: '公元189年秋，洛阳宫门血迹未干，董卓挟西凉兵入京，废立之声已起。京畿人心惶惶，关东州郡暗中观望。你或许在洛阳亲历乱局，或许身在豫州听见风声，旧秩序正在眼前裂开。',
  },
  {
    id: 'bookmark_190_anti_dong',
    label: '190 关东讨董',
    startDate: '190年1月',
    relatedTimelineAnchorIds: ['anchor_190_anti_dong'],
    description: '董卓乱政，关东诸侯起兵讨伐。群雄并起的时代正式开始，何处是你的安身之所？',
    recommendedRegions: ['loc_yingchuan', 'loc_runan', 'loc_nanyang'],
    recommendedOrigins: ['寒门士子', '豪族旁支', '游侠', '县中小吏'],
    situationSummary: '公元190年，董卓废立天子，独霸朝纲。曹操发檄讨董，关东诸侯纷纷响应，推袁绍为盟主。然联军内部各怀异心，观望不前。豫州地处联军后方，各地豪强趁机扩充势力。天下英雄正待崭露头角。',
  },
  {
    id: 'bookmark_194_warlords',
    label: '194 群雄割据',
    startDate: '194年4月',
    relatedTimelineAnchorIds: ['anchor_194_warlords'],
    description: '董卓已死而天下未安，曹操、袁绍、吕布、陶谦、刘备等人各据一方。旧朝廷的名分仍在，真正的权力却落入刀兵之手。',
    recommendedRegions: ['region_yuzhou', 'region_yanzhou', 'region_xuzhou'],
    recommendedOrigins: ['寒门士子', '豪族旁支', '游侠', '流民'],
    situationSummary: '公元194年，关东联军旧梦散尽，诸侯互攻成了常态。兖州、徐州、豫州之间兵灾不断，士族择主，流民迁徙，郡县官府在军阀、豪强与饥民之间摇摆。你要面对的不再是一个乱局，而是多个互相吞噬的乱局。',
  },
  {
    id: 'bookmark_196_emperor_at_xu',
    label: '196 奉迎天子',
    startDate: '196年8月',
    relatedTimelineAnchorIds: ['anchor_196_emperor'],
    description: '献帝东归，曹操迎奉都许。旧汉名分没有消失，却落入新的掌控者手中，忠义与权势第一次如此贴近。',
    recommendedRegions: ['region_yuzhou', 'region_sili', 'region_yanzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '豪族旁支', '游侠'],
    situationSummary: '公元196年，关中残破，天子流离，曹操以迎奉之名把汉廷安置在许县。许都一纸诏令可以让诸侯低头，也可能只是军府手中的利器。颍川、兖州、司隶之间，士人开始重新判断谁能托付，地方豪族也在衡量“奉汉”与“从曹”之间的分寸。你若在此时入局，面对的不是单纯的投靠，而是名分、实权与自保交织的抉择。',
  },
  {
    id: 'bookmark_200_guandu',
    label: '200 官渡前夜',
    startDate: '200年2月',
    relatedTimelineAnchorIds: ['anchor_200_guandu'],
    description: '袁曹对决在即，北方命运悬于一线。站队、投靠、观望，还是另寻出路？',
    recommendedRegions: ['loc_yingchuan', 'loc_runan', 'loc_nanyang'],
    recommendedOrigins: ['寒门士子', '豪族旁支', '游侠', '县中小吏'],
    situationSummary: '公元200年，袁绍兼并河北，拥兵南下。曹操据守许昌，兵微将寡。两大势力对决在即，豫州颍川正处双方势力交错之地。各地士人、豪强纷纷观望择主，每个人都面临着命运的抉择。',
  },
  {
    id: 'bookmark_201_jingzhou_refuge',
    label: '201 荆州寄身',
    startDate: '201年7月',
    relatedTimelineAnchorIds: ['anchor_201_jingzhou_refuge'],
    description: '刘备南依刘表，暂得容身。荆州水土安稳，客将却难真正安身，英雄的低谷也可能是下一段局势的起点。',
    recommendedRegions: ['region_jingzhou', 'region_yuzhou', 'region_xuzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '游侠', '豪族旁支'],
    situationSummary: '公元201年，刘备在中原辗转失利，南下依附刘表。荆州表面富庶安宁，士族门第森严，刘备一行既有仁名，也带着败军和不确定的野心。新野、南郡、江夏之间，曹操的压力从北方逼近，本地豪族却更在意谁会打破眼下平衡。你可以随刘备寄身荆州，也可以是荆州本地人，看见一个无地英雄如何在别人的屋檐下等待时机。',
  },
  {
    id: 'bookmark_207_longzhong_plan',
    label: '207 隆中对',
    startDate: '207年冬',
    relatedTimelineAnchorIds: ['anchor_207_longzhong_plan'],
    description: '刘备三顾茅庐，诸葛亮出山。一个尚无根基的客将集团，第一次拥有了跨荆益、联孙权、抗曹操的长远蓝图。',
    recommendedRegions: ['region_jingzhou', 'region_yizhou', 'region_yangzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '豪族旁支', '游侠'],
    situationSummary: '公元207年冬，荆州仍在刘表治下，北方曹操的阴影已经压到襄阳以北。刘备屡败而不弃，诸葛亮隐居隆中，士人之间流传着卧龙之名。三顾之后，“跨有荆益、联吴抗曹、待天下有变”的道路被说出口，但道路不等于现实：兵少、地狭、寄人篱下，任何一步都可能被本地士族、曹军南下或孙权观望所牵动。你进入的不是胜利前夜，而是一张刚刚展开的艰难蓝图。',
  },
  {
    id: 'bookmark_208_red_cliff',
    label: '208 赤壁风云',
    startDate: '208年10月',
    relatedTimelineAnchorIds: ['anchor_208_red_cliff'],
    description: '曹操南下，荆州易主，孙刘联盟初成。天下一统似在眼前，又似会在长江上翻覆。',
    recommendedRegions: ['region_jingzhou', 'region_yangzhou', 'region_yuzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '游侠', '豪族旁支'],
    situationSummary: '公元208年秋，曹操平定北方后挥军南下，荆州新丧，刘备败走，江东主战主和争论不休。长江两岸的士人、豪族、商旅和流民都在判断：是顺从大势，还是赌一次天下三分的机会。',
  },
  {
    id: 'bookmark_211_entering_shu',
    label: '211 入蜀前夜',
    startDate: '211年12月',
    relatedTimelineAnchorIds: ['anchor_211_entering_shu'],
    description: '刘璋邀刘备入蜀拒张鲁，客军越过山川进入西川。援兵、盟友、外来者、未来主人，身份在栈道尽头变得暧昧。',
    recommendedRegions: ['region_yizhou', 'region_jingzhou', 'region_liangzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '豪族旁支', '游侠'],
    situationSummary: '公元211年，汉中张鲁压在益州北门，刘璋引刘备入蜀以为外援。蜀道艰险，成都富庶，西川旧臣对外来军既盼其拒敌，又惧其夺权；刘备军中也有人明白，这趟入蜀不会只是一次短暂的救援。你可以随军越栈道，也可以身在成都、巴郡或汉中边地，亲眼看见礼节、粮道、军心和野心如何在山川之间相互试探。',
  },
  {
    id: 'bookmark_214_yizhou',
    label: '214 益州风云',
    startDate: '214年6月',
    relatedTimelineAnchorIds: ['anchor_214_yizhou'],
    description: '刘备入蜀，益州换主。西川的门阀、旧臣、商路与山道势力，都要重新排定位置。',
    recommendedRegions: ['region_yizhou', 'region_jingzhou', 'region_yangzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '豪族旁支', '游侠'],
    situationSummary: '公元214年，刘备据益州，蜀地旧臣未必尽服，新附势力也急需立功。成都看似尘埃落定，郡县乡里却还有许多未定之事。你可以是随军入蜀之人，也可以是本地士人、商旅或旁支豪族。',
  },
  {
    id: 'bookmark_219_hanzhong_king',
    label: '219 汉中王业',
    startDate: '219年7月',
    relatedTimelineAnchorIds: ['anchor_219_hanzhong_king'],
    description: '刘备夺汉中、进位汉中王，蜀汉气象一时最盛。可汉中、荆州、江东与曹魏同时牵动，盛势下已藏裂痕。',
    recommendedRegions: ['region_yizhou', 'region_jingzhou', 'region_liangzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '豪族旁支', '边郡武家'],
    situationSummary: '公元219年，定军山余威未散，刘备取得汉中，进位汉中王。成都朝野振奋，益州旧臣、新附荆州人、军中将校都在重新衡量自己的位置；北面曹操虽退，汉中仍是险要前线，东面关羽镇守荆州，孙权与曹魏的视线都盯着这片要地。你身处蜀汉声势最盛之时，却也能听见粮草、边防、盟约和荆州风声里隐隐传来的不稳。',
  },
  {
    id: 'bookmark_220_three_kingdoms',
    label: '220 三国鼎立',
    startDate: '220年12月',
    relatedTimelineAnchorIds: ['anchor_220_three_kingdoms'],
    description: '曹丕代汉，三家天下的形势逐渐清晰。正统、名分、利益与私人命运被重新书写。',
    recommendedRegions: ['region_yuzhou', 'region_yizhou', 'region_yangzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '豪族旁支', '游侠'],
    situationSummary: '公元220年，魏代汉立，旧汉名分崩解。蜀、吴各有盘算，士人必须重新回答忠义与仕途的问题。对于小人物而言，天下大势未必遥远，它可能就是一纸任命、一封密信，或一场不得不选边的婚丧宴席。',
  },
  {
    id: 'bookmark_222_yiling_aftermath',
    label: '222 夷陵败局',
    startDate: '222年7月',
    relatedTimelineAnchorIds: ['anchor_222_yiling_aftermath'],
    description: '夷陵火起，蜀军大败。复仇的旗帜被现实烧穿，旧将、军士、益州百姓都要承受这场失败的回声。',
    recommendedRegions: ['region_yizhou', 'region_jingzhou', 'region_yangzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '流民', '豪族旁支'],
    situationSummary: '公元222年，刘备伐吴在夷陵惨败，水陆军营化作败退与传闻。永安、成都、巴蜀郡县之间，伤兵、遗属、军令和责难接连抵达；东吴守住荆州，曹魏在北方观望，蜀汉不得不从盛极的豪气中退回国本。你可以是败军余部，也可以是益州地方人士，看见一个新生政权如何在大败后维持体面、秩序和人心。',
  },
  {
    id: 'bookmark_223_baidi_regency',
    label: '223 白帝托孤',
    startDate: '223年4月',
    relatedTimelineAnchorIds: ['anchor_223_baidi_regency'],
    description: '刘备病逝白帝城，诸葛亮受托辅政。蜀汉从创业君主的时代转入丞相执政，国丧之后，每个人都要重新站位。',
    recommendedRegions: ['region_yizhou', 'region_jingzhou', 'region_yangzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '豪族旁支', '游侠'],
    situationSummary: '公元223年，白帝城传来刘备托孤与驾崩的消息。成都朝堂必须在悲痛中稳定幼主，益州旧臣观察诸葛亮如何掌权，荆州旧人记着失地，东吴使者也在等待蜀汉是否愿意放下夷陵之怨。你身处这场国丧之后的重整期，看到的不只是忠义故事，还有官署交接、军府整编、豪族试探与百姓对新秩序的迟疑。',
  },
  {
    id: 'bookmark_225_nanzhong_campaign',
    label: '225 南中平定',
    startDate: '225年5月',
    relatedTimelineAnchorIds: ['anchor_225_nanzhong_campaign'],
    description: '诸葛亮南征，七擒孟获成为威服与安抚的象征。蜀汉若要北望中原，必须先让南中归心。',
    recommendedRegions: ['region_yizhou', 'region_jingzhou', 'region_liangzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '边郡武家', '豪族旁支'],
    situationSummary: '公元225年，蜀汉朝局初稳，南中反复未定。诸葛亮亲征南方，山谷、部族、豪帅、郡县官署与军粮道路交织成另一种战场。七擒孟获不只是胜负传闻，更是蜀汉如何对待边地、如何把威服化为归附的考验。你可以随军入南中，也可以出身边郡或地方豪族，在蛮汉交错、山川阻隔与新政权安抚之间寻找自己的位置。',
  },
  {
    id: 'bookmark_228_first_northern_expedition',
    label: '228 初出祁山',
    startDate: '228年3月',
    relatedTimelineAnchorIds: ['anchor_228_first_northern_expedition'],
    description: '诸葛亮第一次北伐，陇右震动，街亭成败牵动全局。蜀汉终于把复兴汉室的旗帜推到魏境边缘。',
    recommendedRegions: ['region_yizhou', 'region_liangzhou', 'region_sili'],
    recommendedOrigins: ['寒门士子', '县中小吏', '边郡武家', '游侠'],
    situationSummary: '公元228年春，诸葛亮出汉中、攻祁山，陇右郡县震动，天水等地人心摇摆，姜维也在这一轮风波中走向蜀汉。可战机并不只在战场，粮道、将令、地方响应和街亭守备都可能改变局势。你若在汉中、陇右或益州后方入局，会同时感到理想的昂扬与军法的冷峻：北伐不再是口号，而是一条会吞噬人命与前程的道路。',
  },
  {
    id: 'bookmark_229_shu_wu_renewed_alliance',
    label: '229 吴蜀复盟',
    startDate: '229年6月',
    relatedTimelineAnchorIds: ['anchor_229_shu_wu_renewed_alliance'],
    description: '孙权称帝，蜀吴重修盟约。夷陵旧怨未消，现实却要求两国重新并肩抗魏。',
    recommendedRegions: ['region_yizhou', 'region_yangzhou', 'region_jingzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '豪族旁支', '游侠'],
    situationSummary: '公元229年，孙权称帝，蜀汉与东吴重新确认盟好。成都需要稳住东线，江东需要承认与制衡，荆州边界上的旧仇却不会因盟书立刻消散。使节往来、商路恢复、边防戒备与朝中议论同时发生。你可以是随使入吴的幕僚、益州官署小吏、江东商旅或荆州旧人，在现实外交与个人恩怨之间看见三国如何维持脆弱平衡。',
  },
  {
    id: 'bookmark_231_qishan_stalemate',
    label: '231 祁山相持',
    startDate: '231年2月',
    relatedTimelineAnchorIds: ['anchor_231_qishan_stalemate'],
    description: '诸葛亮再出祁山，司马懿坚壁相持。胜负之外，粮道、军心和国力正在决定蜀汉北伐能走多远。',
    recommendedRegions: ['region_yizhou', 'region_liangzhou', 'region_sili'],
    recommendedOrigins: ['寒门士子', '县中小吏', '边郡武家', '游侠'],
    situationSummary: '公元231年，诸葛亮再度北伐，祁山一线攻守相持。司马懿不轻易决战，蜀军前线看似稳健，后方粮道却承受巨大压力；益州官署、汉中转运、陇右军情和成都朝议都被拉进同一张网。你身处这个节点，不会只看见阵前旌旗，还会看见一车粮、一纸军令、一次误报如何改变一场持久北伐的重量。',
  },
  {
    id: 'bookmark_234_wuzhangyuan',
    label: '234 五丈原后',
    startDate: '234年9月',
    relatedTimelineAnchorIds: ['anchor_234_wuzhangyuan'],
    description: '诸葛亮病逝，北伐余波未散。蜀汉、曹魏、江东都在等待一个新时代的缝隙。',
    recommendedRegions: ['region_yizhou', 'region_sili', 'region_yangzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '游侠', '豪族旁支'],
    situationSummary: '公元234年，五丈原秋风吹过，蜀军撤归，诸葛亮身后留下未竟之志。曹魏朝堂也非铁板一块，江东守成而心思复杂。旧英雄渐次退场，新一代人物尚未站稳，这是一个适合缝隙中起步的时代。',
  },
  {
    id: 'bookmark_249_gaopingling',
    label: '249 高平陵之变',
    startDate: '249年1月',
    relatedTimelineAnchorIds: ['anchor_249_gaopingling'],
    description: '司马氏政变，曹魏权力中心骤然倾斜。洛阳的沉默比刀兵更可怕。',
    recommendedRegions: ['region_sili', 'region_yuzhou', 'region_jingzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '豪族旁支', '游侠'],
    situationSummary: '公元249年，高平陵事变震动洛阳。曹爽集团倾覆，司马氏掌权，朝中旧交可能一夜成祸。无论你是官署小吏、洛阳士人，还是地方豪族旁支，都可能被卷入清算、投名与自保的旋涡。',
  },
  {
    id: 'bookmark_253_jiangwei_command',
    label: '253 姜维主兵',
    startDate: '253年2月',
    relatedTimelineAnchorIds: ['anchor_253_jiangwei_command'],
    description: '费祎遇刺，姜维用兵空间扩大。蜀汉后期的北伐旗帜再度扬起，朝中守成与主战的裂隙也更清晰。',
    recommendedRegions: ['region_yizhou', 'region_liangzhou', 'region_sili'],
    recommendedOrigins: ['寒门士子', '县中小吏', '边郡武家', '豪族旁支'],
    situationSummary: '公元253年，费祎遇刺，蜀汉朝局震动。姜维获得更大主兵空间，北伐声势再起，但成都朝堂对连年用兵的疑虑也不再隐晦。汉中军府、益州郡县、陇右边境和后主朝廷之间，战功、粮草、将权与国力被反复称量。你可以是姜维麾下军吏、益州后勤官、边郡武家或朝中小臣，在理想仍未熄灭、现实却越来越紧的时代里起步。',
  },
  {
    id: 'bookmark_255_taoxi_victory',
    label: '255 洮西大捷',
    startDate: '255年8月',
    relatedTimelineAnchorIds: ['anchor_255_taoxi_victory'],
    description: '姜维在洮西大破魏军，后期蜀汉少有的大胜传遍朝野。胜利令人振奋，也让补给、国力与下一步选择更加沉重。',
    recommendedRegions: ['region_yizhou', 'region_liangzhou', 'region_sili'],
    recommendedOrigins: ['寒门士子', '县中小吏', '边郡武家', '游侠'],
    situationSummary: '公元255年，姜维北伐在洮西击破魏将王经，捷报传入成都，主战者振奋，守成者沉默而忧惧。陇右战场的胜利没有立刻打开关中门户，却让蜀汉再次看见北伐可能；与此同时，粮道、兵员、朝议和魏军反扑都在逼近。你进入的是一个胜利之后仍未轻松的节点：声望可以上升，风险也会随之加倍。',
  },
  {
    id: 'bookmark_263_shuhan_fall',
    label: '263 蜀汉灭亡',
    startDate: '263年11月',
    relatedTimelineAnchorIds: ['anchor_263_shuhan_fall'],
    description: '钟会、邓艾伐蜀，成都开门。旧国将亡，新局未定，西川人心各有去向。',
    recommendedRegions: ['region_yizhou', 'region_sili', 'region_jingzhou'],
    recommendedOrigins: ['寒门士子', '县中小吏', '流民', '豪族旁支'],
    situationSummary: '公元263年，魏军入蜀，成都降服。降臣、旧将、豪族、军士与百姓都在观察新秩序如何落地。有人准备投魏，有人仍念旧汉，也有人只想保住家人与产业。你身处改朝换代的现场，命运不必跟着旧旗帜一同落下。',
  },
];
