export interface ThreeKingdomsStorySubdomainDefinition {
  id: string;
  label: string;
}

export interface ThreeKingdomsStoryDomainDefinition {
  id: string;
  code: string;
  label: string;
  subdomains: readonly ThreeKingdomsStorySubdomainDefinition[];
  usageBoundary?: string;
}

function subdomains(entries: ReadonlyArray<readonly [string, string]>): ThreeKingdomsStorySubdomainDefinition[] {
  return entries.map(([id, label]) => ({ id, label }));
}

export const THREE_KINGDOMS_STORY_DOMAINS = [
  {
    id: 'military_camp',
    code: 'A',
    label: '军营、军纪与将士生活',
    subdomains: subdomains([
      ['recruitment', '征募'],
      ['unit_integration', '合营'],
      ['training', '训练'],
      ['guard_duty', '值守'],
      ['military_law', '军法'],
      ['rewards_punishments', '赏罚'],
      ['desertion', '逃亡'],
      ['injury_illness', '伤病'],
      ['camp_families', '军中家属'],
      ['officer_relations', '将校关系'],
      ['host_guest_troops', '主客军矛盾'],
    ]),
  },
  {
    id: 'war_pressure',
    code: 'B',
    label: '战斗、战争与军势压力',
    usageBoundary: '只提供冲突前因和战后后果；胜负、伤亡和战果必须来自 Combat / War Engine 或既有结构化事实。',
    subdomains: subdomains([
      ['reconnaissance', '侦察'],
      ['ambush', '伏击'],
      ['pursuit', '追击'],
      ['siege', '围城'],
      ['city_defense', '守城'],
      ['naval_warfare', '水战'],
      ['cavalry_warfare', '骑战'],
      ['mountain_warfare', '山地战'],
      ['night_battle', '夜战'],
      ['withdrawal', '撤军'],
      ['surrender', '请降'],
      ['prisoners', '战俘'],
      ['postwar_merit', '战后争功'],
    ]),
  },
  {
    id: 'logistics',
    code: 'C',
    label: '粮草、辎重与交通',
    subdomains: subdomains([
      ['grain_levy', '征粮'],
      ['warehousing', '仓储'],
      ['transport', '运输'],
      ['horse_fodder', '马料'],
      ['boats', '舟船'],
      ['roads', '道路'],
      ['courier', '驿传'],
      ['arms', '军械'],
      ['ledgers', '账册'],
      ['attrition', '损耗'],
      ['black_market', '盗卖'],
      ['priority_conflict', '优先级争执'],
      ['seasonal_disruption', '季节断运'],
    ]),
  },
  {
    id: 'administration',
    code: 'D',
    label: '州郡治理与官府行政',
    subdomains: subdomains([
      ['seals', '印信'],
      ['documents', '文书'],
      ['old_officials', '旧吏'],
      ['new_officials', '新官'],
      ['tax_labor', '赋役'],
      ['household_registry', '户籍'],
      ['performance_review', '考课'],
      ['amnesty', '赦令'],
      ['requisition', '征发'],
      ['command_chain', '上下级命令'],
      ['frontier_execution', '边地执行'],
      ['government_trust', '官府信誉'],
    ]),
  },
  {
    id: 'justice_security',
    code: 'E',
    label: '司法、治安与刑狱',
    subdomains: subdomains([
      ['banditry', '盗匪'],
      ['clan_fighting', '械斗'],
      ['military_civilian_conflict', '军民冲突'],
      ['accusation', '告发'],
      ['testimony', '证词'],
      ['interrogation', '审讯'],
      ['prison_break', '越狱'],
      ['redemption', '赎罪'],
      ['collective_punishment', '连坐'],
      ['local_mediation', '地方调解'],
      ['law_conflict', '军法与民法冲突'],
    ]),
  },
  {
    id: 'agriculture_disaster',
    code: 'F',
    label: '农业、土地、水利与灾害',
    subdomains: subdomains([
      ['military_farming', '屯田'],
      ['draft_animals', '耕牛'],
      ['farming_season', '农时'],
      ['irrigation', '水渠'],
      ['dikes', '堤防'],
      ['drought_flood', '旱涝'],
      ['locusts', '蝗灾'],
      ['epidemic', '疫病'],
      ['wasteland', '荒地'],
      ['tenancy', '佃作'],
      ['harvest_dispute', '收成争议'],
      ['water_conflict', '军民争水'],
    ]),
  },
  {
    id: 'trade_market',
    code: 'G',
    label: '商贸、市场与货币',
    subdomains: subdomains([
      ['market', '市集'],
      ['grain_price', '粮价'],
      ['salt_iron', '盐铁'],
      ['textiles', '布帛'],
      ['coinage', '铸币'],
      ['credit', '信用'],
      ['lending', '借贷'],
      ['merchants', '商旅'],
      ['checkpoints', '关津'],
      ['smuggling', '走私'],
      ['hoarding', '囤积'],
      ['military_procurement', '军需采购'],
      ['long_distance_trade', '异地贸易'],
    ]),
  },
  {
    id: 'migration_population',
    code: 'H',
    label: '流民、迁徙与人口安置',
    subdomains: subdomains([
      ['city_entry', '入城'],
      ['registration', '附籍'],
      ['hidden_households', '隐户'],
      ['fugitive_households', '逃户'],
      ['forced_migration', '迁民'],
      ['orphans', '孤儿'],
      ['separation', '失散'],
      ['return_home', '归乡'],
      ['military_households', '军户'],
      ['fort_population', '坞堡人口'],
      ['labor_allocation', '劳役分配'],
      ['quarantine', '疫区隔离'],
    ]),
  },
  {
    id: 'clan_local_society',
    code: 'I',
    label: '豪族、宗族与地方社会',
    subdomains: subdomains([
      ['clan_mediation', '宗族调停'],
      ['retainer_dependency', '部曲依附'],
      ['marriage_alliance', '婚姻联盟'],
      ['local_reputation', '乡里名望'],
      ['land_dispute', '土地纠纷'],
      ['private_forces', '私兵'],
      ['donations', '捐输'],
      ['political_exchange', '政治交换'],
      ['old_new_elites', '新旧豪族'],
      ['commoner_advancement', '寒门上升'],
    ]),
  },
  {
    id: 'court_legitimacy',
    code: 'J',
    label: '朝廷、合法性与继承',
    usageBoundary: '只提供通用政治压力，不创建或强迫具体历史政变。',
    subdomains: subdomains([
      ['edict_authenticity', '诏命真伪'],
      ['titles', '官号'],
      ['ritual', '礼仪'],
      ['enfeoffment', '册封'],
      ['succession', '继承'],
      ['regency', '监国'],
      ['powerful_minister', '权臣'],
      ['imperial_clan', '宗室'],
      ['omens', '祥瑞'],
      ['public_opinion', '舆论'],
      ['court_legitimacy', '朝野名分'],
    ]),
  },
  {
    id: 'diplomacy_alliance',
    code: 'K',
    label: '外交、联盟与人质',
    subdomains: subdomains([
      ['envoys', '使者'],
      ['gifts', '礼物'],
      ['oaths', '盟誓'],
      ['passage', '借道'],
      ['joint_campaign', '共同出兵'],
      ['cost_sharing', '军费分摊'],
      ['prisoner_exchange', '俘虏交换'],
      ['hostages', '人质'],
      ['marriage_pact', '婚盟'],
      ['border_dispute', '边界争议'],
      ['truce', '停战'],
      ['double_promises', '双重承诺'],
    ]),
  },
  {
    id: 'intelligence_covert',
    code: 'L',
    label: '情报、谣言与隐秘行动',
    subdomains: subdomains([
      ['scouts', '斥候'],
      ['inside_agents', '内应'],
      ['forged_documents', '假文书'],
      ['interception', '截获'],
      ['leaks', '泄密'],
      ['counterintelligence', '反间'],
      ['rumors', '流言'],
      ['merchant_news', '商旅消息'],
      ['prisoner_testimony', '降卒口供'],
      ['disguise', '身份伪装'],
      ['delayed_report', '迟到军报'],
      ['conflicting_intelligence', '相互矛盾的情报'],
    ]),
  },
  {
    id: 'frontier_ethnic',
    code: 'M',
    label: '边疆与族群关系',
    usageBoundary: '不得把任何族群写成单一性格或固定敌人。',
    subdomains: subdomains([
      ['frontier_trade', '互市'],
      ['frontier_treaty', '盟约'],
      ['submission', '归附'],
      ['chief_authority', '首领权力'],
      ['resettlement', '迁居'],
      ['translation', '翻译'],
      ['customs', '礼俗'],
      ['frontier_army_division', '边军分歧'],
    ]),
  },
  {
    id: 'scholars_ritual',
    code: 'N',
    label: '士人、学术、礼俗与传播',
    subdomains: subdomains([
      ['recommendation', '荐举'],
      ['teacher_student', '师生'],
      ['letters', '书信'],
      ['elite_opinion', '清议'],
      ['reputation', '名声'],
      ['study_travel', '游学'],
      ['classics', '经学'],
      ['copying', '文书抄传'],
      ['sacrifice', '祭祀'],
      ['funeral', '丧礼'],
      ['banquet', '宴饮'],
      ['local_education', '地方教化'],
    ]),
  },
  {
    id: 'family_daily_life',
    code: 'O',
    label: '家庭、日常与关系生活',
    usageBoundary: '成人内容仍受现有年龄、同意和关系门禁，不得由 StoryPack 绕过。',
    subdomains: subdomains([
      ['marriage', '婚姻'],
      ['heirs', '继嗣'],
      ['family_property', '家产'],
      ['family_letters', '家书'],
      ['family_separation', '离散'],
      ['reunion', '团聚'],
      ['master_servant', '主仆'],
      ['neighbors', '邻里'],
      ['caregiving', '疾病照料'],
      ['women_business', '妇女经营'],
      ['inns', '旅舍'],
      ['urban_entertainment', '市井娱乐'],
    ]),
  },
  {
    id: 'aftermath_transition',
    code: 'P',
    label: '战后、灾后与政权更替余波',
    usageBoundary: '必须有战斗、战争、灾害、政权变化或事项终结等既成结构化结果，不得凭空宣告前置事件发生。',
    subdomains: subdomains([
      ['wounded', '伤兵'],
      ['captives', '俘虏'],
      ['remains', '遗骸'],
      ['missing', '失踪'],
      ['revenge', '复仇'],
      ['reconstruction', '重建'],
      ['relief', '赈济'],
      ['arms_recovery', '军械回收'],
      ['old_officials_disposal', '旧官处置'],
      ['public_trust', '百姓信任'],
      ['victory_distribution', '胜利后的内部分配'],
    ]),
  },
] as const satisfies readonly ThreeKingdomsStoryDomainDefinition[];

export const THREE_KINGDOMS_STORY_FACETS = [
  'public_front',
  'private_backdoor',
  'ledger_resources',
  'night_season',
  'familiar_network',
  'rumor_intelligence',
  'deadline_order',
  'aftermath_cost',
  'misidentification',
  'evidence',
  'silence',
  'reversal',
  'interest_conflict',
  'dual_loyalty',
] as const;

export const THREE_KINGDOMS_STORY_ROLE_PERSPECTIVES = [
  'soldier',
  'official',
  'civilian_refugee',
  'merchant_craftsman',
  'scholar_retainer',
  'wanderer_outsider',
  'family_member',
  'envoy_foreigner',
] as const;

export const THREE_KINGDOMS_STORY_ERA_BANDS = [
  { id: '184_191', startYear: 184, endYear: 191 },
  { id: '192_207', startYear: 192, endYear: 207 },
  { id: '208_222', startYear: 208, endYear: 222 },
  { id: '223_249', startYear: 223, endYear: 249 },
  { id: '250_280', startYear: 250, endYear: 280 },
] as const;

export const THREE_KINGDOMS_STORY_REGIONS = [
  'north_plain',
  'frontier',
  'guanzhong',
  'bashu',
  'jingxiang',
  'jiangdong',
  'huainan',
  'nanzhong',
] as const;

export const THREE_KINGDOMS_STORY_PACK_CATALOG = {
  domains: THREE_KINGDOMS_STORY_DOMAINS,
  facets: THREE_KINGDOMS_STORY_FACETS,
  rolePerspectives: THREE_KINGDOMS_STORY_ROLE_PERSPECTIVES,
  eraBands: THREE_KINGDOMS_STORY_ERA_BANDS,
} as const;
