import type { TimelineAnchor } from '../../engine/types';

/**
 * 三国时代锚点
 * 不是固定剧本，不强制剧情发生，只告知系统当前时代附近的历史气候
 */
export const threeKingdomsTimelineAnchors: TimelineAnchor[] = [
  {
    id: 'anchor_184_yellow_turban',
    label: '184 黄巾初起',
    approximateDate: '184年春',
    summary: '张角以"苍天已死，黄天当立，岁在甲子，天下大吉"为号，发动大规模起义。黄巾军遍及八州，天下震动。汉廷紧急动员，各地募兵自保。',
    activeFactionHints: ['太平道（黄巾军）', '汉廷（中央）', '地方官府', '各地豪族'],
    regionalTensionHints: ['冀州（起义策源地）', '豫州（波及严重）', '青州（响应激烈）', '兖州（战乱纷起）'],
    suggestedThemes: ['乱世序幕', '秩序崩塌', '生存抉择', '天下何往'],
  },
  {
    id: 'anchor_189_dong_zhuo',
    label: '189 董卓入京',
    approximateDate: '189年秋',
    summary: '灵帝驾崩，何进被杀，宦官覆灭。董卓率西凉军入洛阳，废少帝立献帝，把持朝政。天下诸侯各怀异心。',
    activeFactionHints: ['董卓集团', '汉廷（傀儡）', '各地诸侯', '在野士人'],
    regionalTensionHints: ['司隶（洛阳混乱）', '凉州（董卓根基）', '关东诸侯（暗中串联）'],
    suggestedThemes: ['朝纲崩坏', '群雄并起', '挟天子', '忠奸之辨'],
  },
  {
    id: 'anchor_190_anti_dong',
    label: '190 关东讨董',
    approximateDate: '190年春',
    summary: '曹操发檄文，关东诸侯组成讨董联军，推袁绍为盟主。然各怀私心，相互观望，联军不久瓦解。天下正式进入群雄割据时代。',
    activeFactionHints: ['关东联军', '董卓集团', '各地观望势力'],
    regionalTensionHints: ['司隶（前线）', '豫州（联军后方）', '兖州（曹操崛起）'],
    suggestedThemes: ['群雄逐鹿', '合纵连横', '野心与仁义', '乱世英雄'],
  },
  {
    id: 'anchor_194_warlords',
    label: '194 群雄割据',
    approximateDate: '194年',
    summary: '董卓已死，李傕郭汜把持关中，关东诸侯互相攻伐。曹操据兖州，袁绍据河北，吕布、陶谦、刘备等人在中原缝隙中起落。',
    activeFactionHints: ['曹操集团', '袁绍集团', '吕布势力', '徐州陶谦旧部', '各地豪族'],
    regionalTensionHints: ['兖州（争夺激烈）', '徐州（兵灾将至）', '豫州（多方交错）'],
    suggestedThemes: ['军阀混战', '择主与自保', '流民潮', '地方秩序重组'],
  },
  {
    id: 'anchor_196_emperor',
    label: '196 奉迎天子',
    approximateDate: '196年',
    summary: '曹操迎献帝于许昌，"挟天子以令诸侯"。荀彧等谋士归附，曹操势力急剧壮大。袁绍后悔莫及。',
    activeFactionHints: ['曹操集团', '袁绍集团', '汉廷（许昌）', '各地军阀'],
    regionalTensionHints: ['豫州（曹操根据地）', '冀州（袁绍大本营）', '司隶（残破）'],
    suggestedThemes: ['正统之争', '谋士与明主', '权力合法性', '南北对峙前奏'],
  },
  {
    id: 'anchor_200_guandu',
    label: '200 官渡前夜',
    approximateDate: '200年春',
    summary: '袁绍兼并河北四州，拥兵十万，虎视中原。曹操据守许昌，兵微将寡，但上下齐心。一场决定北方命运的大战即将爆发。',
    activeFactionHints: ['袁绍集团', '曹操集团', '刘备（寄居汝南）', '孙权（初继江东）'],
    regionalTensionHints: ['豫州（对峙前线）', '冀州（袁绍后方）', '扬州（孙权稳固江东）'],
    suggestedThemes: ['以弱对强', '命运抉择', '谋略与勇武', '生死存亡'],
  },
  {
    id: 'anchor_201_jingzhou_refuge',
    label: '201 荆州寄身',
    approximateDate: '201年',
    summary: '刘备在汝南等地受挫后南依刘表，寄居荆州。此时他名望尚在而基业未成，既被礼遇，也受提防。',
    activeFactionHints: ['刘备集团', '刘表荆州', '曹操集团', '荆州士族'],
    regionalTensionHints: ['荆州（表面安稳）', '豫州（曹操压力）', '江夏与南郡（客将去留）'],
    suggestedThemes: ['寄人篱下', '英雄低谷', '士人观望', '客将与本土势力'],
  },
  {
    id: 'anchor_207_longzhong_plan',
    label: '207 隆中对',
    approximateDate: '207年冬',
    summary: '刘备三顾茅庐，诸葛亮出山，提出跨有荆益、联吴抗曹、待天下有变的战略。刘备集团第一次拥有清晰的长期蓝图。',
    activeFactionHints: ['刘备集团', '诸葛亮与荆州士人', '刘表荆州', '曹操集团', '孙权集团'],
    regionalTensionHints: ['荆州（人才与地利交汇）', '益州（远方目标）', '扬州（未来盟友）'],
    suggestedThemes: ['明主与谋臣', '三分蓝图', '低谷中的远志', '荆益之望'],
  },
  {
    id: 'anchor_208_red_cliff',
    label: '208 赤壁前夜',
    approximateDate: '208年秋',
    summary: '曹操统一北方，率大军南征荆州。刘表病逝，刘琮投降。刘备败走当阳，诸葛亮出使江东。孙刘联盟即将成形。',
    activeFactionHints: ['曹操集团', '孙权集团', '刘备集团', '刘表旧部'],
    regionalTensionHints: ['荆州（前线）', '扬州（江东基地）', '豫州（曹操后方）'],
    suggestedThemes: ['天下三分前夜', '联盟与背叛', '以弱抗强', '英雄际会'],
  },
  {
    id: 'anchor_211_entering_shu',
    label: '211 入蜀前夜',
    approximateDate: '211年',
    summary: '刘璋邀刘备入蜀以拒汉中张鲁，刘备由荆州转向益州。入蜀既是援兵，也是夺取西川的机会。',
    activeFactionHints: ['刘备集团', '刘璋益州', '张鲁汉中', '荆州留守势力', '蜀中豪族'],
    regionalTensionHints: ['益州（引客入境）', '汉中（北门压力）', '荆州（后方牵挂）'],
    suggestedThemes: ['客军入蜀', '名义与实利', '蜀中旧臣', '山川险阻'],
  },
  {
    id: 'anchor_214_yizhou',
    label: '214 益州易主',
    approximateDate: '214年',
    summary: '刘备夺取益州，刘璋出降。蜀地旧臣、豪族、商旅与军府都需重新适应新政权。',
    activeFactionHints: ['刘备集团', '益州旧臣', '地方豪族', '汉中张鲁势力'],
    regionalTensionHints: ['益州（新旧交接）', '荆州（孙刘关系紧张）', '汉中（北方压力）'],
    suggestedThemes: ['新政权立足', '旧臣去留', '蜀地豪族', '边地机会'],
  },
  {
    id: 'anchor_219_hanzhong_king',
    label: '219 汉中王业',
    approximateDate: '219年夏',
    summary: '刘备夺取汉中，进位汉中王，蜀汉势力达到高峰。与此同时荆州前线牵动孙权、曹操与关羽，盛势之下暗伏裂痕。',
    activeFactionHints: ['刘备集团', '曹操集团', '关羽荆州军', '孙权集团', '益州军府'],
    regionalTensionHints: ['汉中（新夺要地）', '荆州（大战将起）', '益州（称王后方）'],
    suggestedThemes: ['王业高峰', '汉中门户', '盛极伏危', '蜀汉根基'],
  },
  {
    id: 'anchor_220_three_kingdoms',
    label: '220 三国鼎立',
    approximateDate: '220年',
    summary: '曹丕代汉称帝，汉室名义终结。蜀、吴相继调整战略，三国鼎立格局逐渐成形。',
    activeFactionHints: ['曹魏', '蜀汉', '东吴', '旧汉臣僚'],
    regionalTensionHints: ['豫州（曹魏腹地）', '益州（蜀汉根本）', '扬州（东吴江东）'],
    suggestedThemes: ['正统之争', '新朝秩序', '士人选择', '三分天下'],
  },
  {
    id: 'anchor_222_yiling_aftermath',
    label: '222 夷陵败局',
    approximateDate: '222年夏',
    summary: '刘备伐吴在夷陵惨败，蜀汉精锐与旧将折损甚重。东吴守住荆州，蜀汉必须在复仇、收拾残局与保住国本之间选择。',
    activeFactionHints: ['蜀汉', '东吴', '曹魏', '荆州吴军', '益州军府'],
    regionalTensionHints: ['荆州（三峡与江陵一线）', '益州（败军回撤）', '扬州（吴国转守）'],
    suggestedThemes: ['大败之后', '复仇代价', '国本收缩', '旧将凋零'],
  },
  {
    id: 'anchor_223_baidi_regency',
    label: '223 白帝托孤',
    approximateDate: '223年春',
    summary: '刘备病逝白帝城，托孤诸葛亮。蜀汉由昭烈开创转入丞相辅政，幼主、旧臣、新附益州势力都要重新定位。',
    activeFactionHints: ['蜀汉后主朝廷', '诸葛亮丞相府', '益州旧臣', '东吴', '曹魏'],
    regionalTensionHints: ['益州（政权交接）', '永安（托孤现场）', '荆州（三国边界）'],
    suggestedThemes: ['托孤与辅政', '新旧臣僚', '国丧之后', '蜀汉重整'],
  },
  {
    id: 'anchor_225_nanzhong_campaign',
    label: '225 南中平定',
    approximateDate: '225年',
    summary: '诸葛亮南征南中，平定地方反叛与豪帅割据，七擒孟获成为安抚边地的象征。蜀汉后方由此相对稳定。',
    activeFactionHints: ['蜀汉', '南中豪帅', '益州郡县', '诸葛亮丞相府'],
    regionalTensionHints: ['益州南部（山川部族）', '成都（后方整合）', '越巂牂柯一带（归附未稳）'],
    suggestedThemes: ['南中归附', '安抚与威服', '边地豪帅', '北伐后方'],
  },
  {
    id: 'anchor_228_first_northern_expedition',
    label: '228 初出祁山',
    approximateDate: '228年春',
    summary: '诸葛亮第一次北伐，陇右震动，天水等地响应，马谡失街亭导致战机流失。蜀汉攻魏路线正式展开。',
    activeFactionHints: ['蜀汉北伐军', '曹魏陇右守军', '姜维初归蜀', '益州后勤'],
    regionalTensionHints: ['陇右（响应与反扑）', '汉中（出兵门户）', '益州（粮草压力）'],
    suggestedThemes: ['北伐初战', '街亭失守', '新人归附', '理想与军法'],
  },
  {
    id: 'anchor_229_shu_wu_renewed_alliance',
    label: '229 吴蜀复盟',
    approximateDate: '229年',
    summary: '孙权称帝后，蜀吴重新确认盟约，共同制衡曹魏。夷陵旧怨未消，但蜀汉必须稳住东线，才能继续北伐。',
    activeFactionHints: ['蜀汉', '东吴', '曹魏', '诸葛亮丞相府', '江东朝廷'],
    regionalTensionHints: ['益州（北伐准备）', '扬州（吴国新帝号）', '荆州（旧怨边界）'],
    suggestedThemes: ['旧怨重盟', '现实外交', '两线取舍', '抗魏格局'],
  },
  {
    id: 'anchor_231_qishan_stalemate',
    label: '231 祁山相持',
    approximateDate: '231年',
    summary: '诸葛亮再出祁山，与司马懿相持，粮运与后勤成为战局关键。前线胜负之外，蜀汉内部的承压也逐渐显现。',
    activeFactionHints: ['蜀汉北伐军', '曹魏关陇军', '司马懿势力', '益州后勤官署'],
    regionalTensionHints: ['祁山（攻守相持）', '汉中（粮道节点）', '益州（后勤紧绷）'],
    suggestedThemes: ['持久北伐', '粮道压力', '谨慎与冒进', '国力消耗'],
  },
  {
    id: 'anchor_234_wuzhangyuan',
    label: '234 五丈原后',
    approximateDate: '234年秋',
    summary: '诸葛亮病逝五丈原，蜀汉北伐退潮。曹魏内部权力仍在暗流中酝酿，东吴守成观望。',
    activeFactionHints: ['蜀汉后主朝廷', '曹魏朝廷', '司马氏势力', '东吴'],
    regionalTensionHints: ['益州（北伐余波）', '司隶（曹魏中枢）', '扬州（江东守成）'],
    suggestedThemes: ['旧英雄退场', '权臣伏线', '遗志与现实', '边地人心'],
  },
  {
    id: 'anchor_249_gaopingling',
    label: '249 高平陵之变',
    approximateDate: '249年正月',
    summary: '司马懿发动高平陵政变，曹爽集团覆灭，曹魏权力结构发生根本变化。',
    activeFactionHints: ['司马氏', '曹魏宗室', '曹爽旧党', '地方官僚'],
    regionalTensionHints: ['司隶（政变中心）', '豫州（曹魏腹地）', '荆州（边镇观望）'],
    suggestedThemes: ['政变清算', '门阀站队', '朝堂恐惧', '沉默中的改朝'],
  },
  {
    id: 'anchor_253_jiangwei_command',
    label: '253 姜维主兵',
    approximateDate: '253年',
    summary: '费祎遇刺后，姜维获得更大军事空间，蜀汉后期北伐路线转向主动。朝中对用兵、国力与守成的争论也更尖锐。',
    activeFactionHints: ['蜀汉后主朝廷', '姜维北伐军', '曹魏关陇军', '益州守成派'],
    regionalTensionHints: ['益州（朝议分歧）', '汉中（出兵门户）', '陇右（北伐目标）'],
    suggestedThemes: ['后期北伐', '主战与守成', '将权上升', '国力边界'],
  },
  {
    id: 'anchor_255_taoxi_victory',
    label: '255 洮西大捷',
    approximateDate: '255年',
    summary: '姜维北伐在洮西击破魏将王经，取得后期蜀汉少有的大胜。但胜利未能转化为根本局面，补给与国内疑虑仍在加重。',
    activeFactionHints: ['姜维北伐军', '曹魏关陇军', '蜀汉朝廷', '陇右地方势力'],
    regionalTensionHints: ['陇西洮西（战场）', '汉中（后勤门户）', '益州（国力压力）'],
    suggestedThemes: ['大捷与代价', '姜维声望', '补给极限', '胜而未定'],
  },
  {
    id: 'anchor_263_shuhan_fall',
    label: '263 蜀汉灭亡',
    approximateDate: '263年冬',
    summary: '钟会、邓艾伐蜀，刘禅出降，蜀汉灭亡。蜀地旧臣、军民与豪族进入新秩序前夜。',
    activeFactionHints: ['曹魏伐蜀军', '蜀汉降臣', '钟会势力', '邓艾势力', '益州地方豪族'],
    regionalTensionHints: ['益州（改朝换代）', '司隶（战后处置）', '荆州（吴国震动）'],
    suggestedThemes: ['亡国现场', '投降与守节', '新旧秩序', '乱局余波'],
  },
];
