import { PROMPT_CONTENT_VIEWS } from './PromptContentTemplates';

export type PromptRiskLevel = 'low' | 'medium' | 'high';

export type PromptEditLevel = 'safe' | 'advanced' | 'locked';

export type PromptContentViewType = 'fullText' | 'template' | 'summaryOnly' | 'lockedProtocol';

export type PromptRegistryCategory =
  | 'main.system'
  | 'main.userProtocol'
  | 'main.narrativeStyle'
  | 'main.stateWriter'
  | 'opening.trueOpening'
  | 'npc.profileWriteback'
  | 'npc.memoryWriteback'
  | 'npc.intentSimulation'
  | 'femaleProfile.writeback'
  | 'nsfw.adultIntimacy'
  | 'map.writeback'
  | 'memory.contextProjection'
  | 'memory.summaryCompression'
  | 'worldbook.prompts'
  | 'settings.taskDescriptions';

export interface PromptRegistryEntry {
  id: string;
  category: PromptRegistryCategory;
  title: string;
  description: string;
  sourceFile: string;
  sourceSymbol?: string;
  usedBy: string[];
  order: number;
  riskLevel: PromptRiskLevel;
  editLevel: PromptEditLevel;
  runtimeUsed: boolean;
  protocolBound: boolean;
  worldbookBound?: boolean;
  defaultContentPreview?: string;
  notes?: string;
  displayTitleZh?: string;
  displayCategoryZh?: string;
  userFacingDescription?: string;
  contentViewType?: PromptContentViewType;
  defaultContent?: string;
  defaultContentTemplate?: string;
  contentNotes?: string;
}

export interface PromptRegistryContentView {
  displayTitleZh: string;
  displayCategoryZh: string;
  userFacingDescription: string;
  contentViewType: PromptContentViewType;
  defaultContent?: string;
  defaultContentTemplate?: string;
  contentNotes?: string;
}

const runtimeOverridePromptIds = new Set([
  'worldbook.narrativeBaseline',
  'worldbook.toneGuide',
  'main.systemPrompt',
  'worldline.knowledgeProjectionPolicy',
  'main.factEvidenceGate',
  'main.uniqueArtProgressionProtocol',
  'main.userPrompt',
  'main.narrativeProseStyleGuide',
  'main.narrativeProseFinalReview',
  'main.relationshipThreadProjectionGuide',
  'main.stateWriterProtocol',
  'opening.trueOpeningPrompt',
  'opening.extraRequestPriority',
  'opening.identityProfileProtocol',
  'opening.reputationProtocol',
  'opening.factionLedgerProtocol',
  'opening.traitResolutionProtocol',
  'opening.uniqueArtsProtocol',
  'opening.loadoutProtocol',
  'opening.holdingAssetProtocol',
  'opening.femaleNpcProfileProtocol',
  'nsfw.adultIntimacy.commonProtocol',
  'memory.summaryCompressionSystemPrompt',
  'memory.summaryCompressionUserPrompt',
  'npcSimulation.systemPrompt',
  'npcSimulation.userPrompt',
]);

const promptRegistry: readonly PromptRegistryEntry[] = [
  {
    id: 'worldbook.prompts',
    category: 'worldbook.prompts',
    title: 'Worldbook prompt bundle',
    description: 'Worldbook narrative baseline, tone guide, forbidden topics, and output format metadata.',
    sourceFile: 'src/worldbooks/threeKingdoms/prompts.ts',
    sourceSymbol: 'threeKingdomsPrompts',
    usedBy: ['PromptComposer.composePrompt'],
    order: 10,
    riskLevel: 'low',
    editLevel: 'safe',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: true,
    defaultContentPreview: 'Uses narrativeBaseline, toneGuide, forbiddenTopics, and outputFormat from the active worldbook.',
    notes: 'This is worldbook-scoped content and should move with future era packs.',
  },
  {
    id: 'worldbook.narrativeBaseline',
    category: 'worldbook.prompts',
    title: 'Worldbook narrative baseline',
    description: 'Era-specific narration baseline used by the main system prompt.',
    sourceFile: 'src/worldbooks/threeKingdoms/prompts.ts',
    sourceSymbol: 'threeKingdomsPrompts.narrativeBaseline',
    usedBy: ['PromptComposer.composePrompt'],
    order: 20,
    riskLevel: 'low',
    editLevel: 'safe',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: true,
    defaultContentPreview: 'Narrative baseline for the active worldbook.',
  },
  {
    id: 'worldbook.toneGuide',
    category: 'worldbook.prompts',
    title: 'Worldbook tone guide',
    description: 'Era-specific tone and prose style guidance.',
    sourceFile: 'src/worldbooks/threeKingdoms/prompts.ts',
    sourceSymbol: 'threeKingdomsPrompts.toneGuide',
    usedBy: ['PromptComposer.composePrompt'],
    order: 30,
    riskLevel: 'low',
    editLevel: 'safe',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: true,
    defaultContentPreview: 'Tone guide for the active worldbook.',
  },
  {
    id: 'main.systemPrompt',
    category: 'main.system',
    title: 'Main system prompt',
    description: 'Top-level main turn system prompt assembled from worldbook content, era anchors, opening context, crisis context, and output rules.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['TurnOrchestrator.generateNarratorResponse', 'TurnOrchestrator.buildTurnMessages'],
    order: 100,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: true,
    notes: 'Registry records the source location only; the long template remains in PromptComposer.',
  },
  {
    id: 'worldline.knowledgeProjectionPolicy',
    category: 'main.system',
    title: 'Worldline knowledge projection policy',
    description: 'Boundary and priority policy for KnowledgeBase and StoryPack hints in the main turn prompt.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['PromptComposer.composePrompt'],
    order: 105,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    worldbookBound: true,
    defaultContentPreview: 'KnowledgeBase and StoryPack hints are references, not rails.',
    notes: 'Controls whether historical/original-source references can override local save facts. Keep locked by default.',
  },
  {
    id: 'main.factEvidenceGate',
    category: 'main.system',
    title: 'Global fact and evidence gate',
    description: 'Treats player input as an intent or claim and requires established causal evidence before persistent state changes.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['PromptComposer.composePrompt', 'PromptComposer.generateStateWriterContext'],
    order: 107,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    worldbookBound: false,
    defaultContentPreview: 'Player claims are not facts; material state writeback requires an established source and result.',
    notes: 'Global gate for all material state domains. Domain validators remain responsible for stable IDs and bounded fields.',
  },
  {
    id: 'main.uniqueArtProgressionProtocol',
    category: 'main.system',
    title: 'Unique art local progression protocol',
    description: 'Requires structured progress evidence and reserves level/progress settlement for the local engine.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['PromptComposer.composePrompt', 'PromptComposer.generateStateWriterContext'],
    order: 108,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    worldbookBound: false,
    defaultContentPreview: 'Existing unique art levels and progress are locally settled from structured evidence events.',
  },
  {
    id: 'main.userPrompt',
    category: 'main.userProtocol',
    title: 'Main user prompt and response protocol',
    description: 'Main turn user prompt containing runtime state, player input, response JSON requirements, and writeback schema.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['TurnOrchestrator.generateNarratorResponse', 'TurnOrchestrator.buildTurnMessages'],
    order: 110,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'High risk because it binds protocolVersion, statePatches, statePatch, and writeback shape.',
  },
  {
    id: 'main.narrativeProseStyleGuide',
    category: 'main.narrativeStyle',
    title: 'Narrative prose style guide',
    description: 'Runtime prose guide that improves ordinary narrativeText scene presence, NPC response, consequence, limited perspective, and turn ending.',
    sourceFile: 'src/engine/prompts/PromptContentTemplates.ts',
    sourceSymbol: 'NARRATIVE_PROSE_STYLE_GUIDE_TEMPLATE',
    usedBy: ['PromptComposer.composePrompt'],
    order: 115,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: false,
    defaultContentPreview: 'Guide for richer ordinary narrative prose without changing JSON/writeback protocol.',
  },
  {
    id: 'main.relationshipThreadProjectionGuide',
    category: 'main.narrativeStyle',
    title: 'Relationship thread projection guide',
    description: 'Runtime guidance for using established heroine and bond threads as compact prose continuity anchors.',
    sourceFile: 'src/engine/prompts/PromptContentTemplates.ts',
    sourceSymbol: 'RELATIONSHIP_THREAD_PROJECTION_GUIDE_TEMPLATE',
    usedBy: ['PromptComposer.composePrompt', 'selectPromptContext'],
    order: 116,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: false,
    defaultContentPreview: 'Established heroine/bond threads are continuity anchors, not a task pool.',
  },
  {
    id: 'main.narrativeProseFinalReview',
    category: 'main.narrativeStyle',
    title: 'Narrative prose same-generation final review',
    description: 'Silent same-generation review for recent-pattern repetition, purposeless prose, invented player decisions, and redundant explanatory summary.',
    sourceFile: 'src/engine/prompts/PromptContentTemplates.ts',
    sourceSymbol: 'NARRATIVE_PROSE_FINAL_REVIEW_TEMPLATE',
    usedBy: ['PromptComposer.composePrompt', 'TurnOrchestrator.buildTurnMessages'],
    order: 117,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: false,
    defaultContentPreview: 'One silent prose review in the main response, before the adult final reminder and without a second API call.',
  },
  {
    id: 'main.narrativeContext',
    category: 'main.system',
    title: 'Current narrative context projection',
    description: 'Runtime projection of date, place, player archive, map, memory, NPCs, recent events, rumors, quests, and local situation.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'generateNarrativeContext',
    usedBy: ['PromptComposer.composePrompt'],
    order: 120,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
    notes: 'Projection template rather than an editable prompt source.',
  },
  {
    id: 'main.finalTurnMessages',
    category: 'main.userProtocol',
    title: 'Final main turn message wrapper',
    description: 'Final LLM messages wrapper combining system prompt, user prompt, state writer context, and JSON-only output requirements.',
    sourceFile: 'src/engine/turn/TurnOrchestrator.ts',
    sourceSymbol: 'buildTurnMessages',
    usedBy: ['TurnOrchestrator.generateNarratorResponse'],
    order: 130,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Changing this can break JSON response parsing and state writeback.',
  },
  {
    id: 'main.timeAdvanceRepairPrompt',
    category: 'main.userProtocol',
    title: 'Time advance repair prompt',
    description: 'Conditional JSON repair prompt used when the main response lacks a valid timeAdvance patch.',
    sourceFile: 'src/engine/turn/TurnOrchestrator.ts',
    sourceSymbol: 'buildTimeAdvanceRepairMessages',
    usedBy: ['TurnOrchestrator.requestTimeAdvanceRepair'],
    order: 140,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Locked because it preserves narrativeText, suggestedActions, writeback, and repairs statePatches.',
  },
  {
    id: 'time.advanceProtocol',
    category: 'main.stateWriter',
    title: 'Time advance protocol',
    description: 'Rules for LLM-proposed in-game time advancement through timeAdvance patches.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt/generateStateWriterContext',
    usedBy: ['PromptComposer.composePrompt', 'TurnOrchestrator.requestTimeAdvanceRepair', 'StatePatchApplier.applyPatches'],
    order: 150,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Static protocol documentation for prompt management and token estimation; runtime text is assembled in PromptComposer and TurnOrchestrator.',
  },
  {
    id: 'time.derivedAgeProtocol',
    category: 'main.stateWriter',
    title: 'Derived NPC age protocol',
    description: 'Rules for treating complete birthDate as the persisted source of truth and deriving current age without batch-writing NPC ages.',
    sourceFile: 'src/engine/time/npcAge.ts',
    sourceSymbol: 'deriveNpcCurrentAge',
    usedBy: ['luanshiReducers.applyNpcFemaleProfileUpdate', 'npcPanelModel.buildNpcPanelModel', 'PromptComposer.formatNpcFemaleProfile'],
    order: 160,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Locked because it controls adult female profile visibility and prompt projection gates.',
  },
  {
    id: 'main.stateWriterProtocol',
    category: 'main.stateWriter',
    title: 'State writer protocol',
    description: 'State writer context containing current IDs, canonical location identity, allowed commands, and structured writeback rules.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'generateStateWriterContext',
    usedBy: ['PromptComposer.composePrompt', 'TurnOrchestrator.buildTurnMessages'],
    order: 200,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Strongly bound to StatePatch, LuanShiCommand, validators, and reducers.',
  },
  {
    id: 'holding.ledgerWritebackProtocol',
    category: 'main.stateWriter',
    title: 'Holding ledger writeback protocol',
    description: 'upsertHoldingLedger command rules for player/self-faction controlled holdings, civil scope, revenue-related corruption, and non-September levy consequences.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'generateStateWriterContext',
    usedBy: ['PromptComposer.composePrompt', 'luanshiReducers.applyHoldingLedgerUpsert'],
    order: 210,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Locked because it controls persistent holding IDs, annual settlement inputs, and troop/faction boundaries.',
  },
  {
    id: 'holding.domesticReportProtocol',
    category: 'main.stateWriter',
    title: 'Domestic report writeback protocol',
    description: 'upsertDomesticReport command rules for model-authored special reports and the reserved local system namespace.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'generateStateWriterContext',
    usedBy: ['PromptComposer.composePrompt', 'luanshiReducers.applyDomesticReportUpsert'],
    order: 220,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Locked because local resource truth and LLM-written report narration must stay separated.',
  },
  {
    id: 'opening.trueOpeningPrompt',
    category: 'opening.trueOpening',
    title: 'True opening prompt',
    description: 'Synthetic player input that asks the main turn pipeline to generate the first playable opening scene.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening', 'TurnOrchestrator.executeTurn'],
    order: 300,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    worldbookBound: true,
    notes: 'Uses the main turn prompt pipeline and includes opening-specific writeback instructions.',
  },
  {
    id: 'opening.extraRequestPriority',
    category: 'opening.trueOpening',
    title: 'Opening extra request priority',
    description: 'Instruction that player opening extra request has highest priority and should be reconciled with ordinary opening options.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening'],
    order: 310,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
  },
  {
    id: 'opening.identityProfileProtocol',
    category: 'opening.trueOpening',
    title: 'Opening identity and profile concretization protocol',
    description: 'Opening-time protocol requiring conceptual player origin, identity, appearance, and personality to be concretized through updateCharacterIdentity.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening'],
    order: 315,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'opening.reputationProtocol',
    category: 'opening.trueOpening',
    title: 'Opening reputation carryover protocol',
    description: 'Opening-time protocol requiring seeded fame and morality to shape narrative reactions and controlled reputation writeback.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening'],
    order: 317,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'opening.factionLedgerProtocol',
    category: 'opening.trueOpening',
    title: 'Opening faction ledger protocol',
    description: 'Opening-time protocol requiring current-era faction facts to be written through upsertFactionLedger when established by the opening.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening', 'TurnOrchestrator.executeTurn'],
    order: 318,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    worldbookBound: true,
  },
  {
    id: 'opening.traitResolutionProtocol',
    category: 'opening.trueOpening',
    title: 'Opening trait resolution protocol',
    description: 'Opening-time protocol for resolving custom trait rarity through updatePlayerTraits.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening'],
    order: 320,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'opening.uniqueArtsProtocol',
    category: 'opening.trueOpening',
    title: 'Opening unique arts protocol',
    description: 'Opening-time protocol requiring the model to create initial unique arts with updateCharacterUniqueArts.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening'],
    order: 325,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'opening.loadoutProtocol',
    category: 'opening.trueOpening',
    title: 'Opening loadout protocol',
    description: 'Opening-time instruction requiring the model to create initial loadout with updatePlayerLoadout.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening'],
    order: 330,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'opening.holdingAssetProtocol',
    category: 'opening.trueOpening',
    title: 'Opening holding and private asset boundary protocol',
    description: 'Opening-time instruction that distinguishes controlled holdings, private assets, and personal loadout to prevent invented local treasury values.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening', 'TurnOrchestrator.executeTurn'],
    order: 335,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'opening.femaleNpcProfileProtocol',
    category: 'opening.trueOpening',
    title: 'Opening female NPC profile protocol',
    description: 'Opening-time instruction for eligible female NPC profile creation using the same npcId.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening'],
    order: 340,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Also represented by femaleProfile.openingFemaleNpcProfileProtocol for category lookup.',
  },
  {
    id: 'npc.profileSuggestionsSchema',
    category: 'npc.profileWriteback',
    title: 'NPC profile suggestions schema',
    description: 'writeback.npcProfileSuggestions schema for creating or updating NPC archive candidates.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['NarratorResponseParser.parseNarratorResponse', 'NarratorWritebackApplier.applyNarratorWriteback'],
    order: 400,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'npc.profileWritebackProtocol',
    category: 'npc.profileWriteback',
    title: 'NPC profile writeback protocol',
    description: 'upsertNpcProfile command rules including required NPC fields, age, ability scores, traits, and profile stability.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'generateStateWriterContext',
    usedBy: ['NarratorWritebackApplier.applyNarratorWriteback', 'StatePatchValidator.validateStatePatch'],
    order: 410,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'npc.currentNpcProjection',
    category: 'npc.profileWriteback',
    title: 'Current NPC projection',
    description: 'Narrative projection of present and focused NPC profiles for the main model.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'formatNpcNarrative',
    usedBy: ['PromptComposer.generateNarrativeContext'],
    order: 420,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
  },
  {
    id: 'npc.idStabilityContext',
    category: 'npc.profileWriteback',
    title: 'NPC ID stability context',
    description: 'State writer projection of NPC ids and names to prevent drift when updating existing NPCs.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'formatNpcStateWriterLine',
    usedBy: ['PromptComposer.generateStateWriterContext'],
    order: 430,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'npc.memoryWritebackProtocol',
    category: 'npc.memoryWriteback',
    title: 'NPC memory writeback protocol',
    description: 'Rules for writeback.npcMemorySuggestions and pushNpcMemory command creation.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt/generateStateWriterContext',
    usedBy: ['NarratorResponseParser.parseNarratorResponse', 'NarratorWritebackApplier.applyNarratorWriteback'],
    order: 500,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'npcSimulation.systemPrompt',
    category: 'npc.intentSimulation',
    title: 'NPC dynamic simulation system prompt',
    description: 'System prompt for optional NPC intent pre-processing before the main narrative turn.',
    sourceFile: 'src/engine/npc/NpcIntentSimulation.ts',
    sourceSymbol: 'buildNpcIntentSimulationMessages',
    usedBy: ['NpcIntentSimulation.executeNpcIntentSimulation'],
    order: 540,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Locked because it defines the advisory-only boundary and forbids state writeback from the helper model.',
  },
  {
    id: 'npcSimulation.userPrompt',
    category: 'npc.intentSimulation',
    title: 'NPC dynamic simulation user prompt',
    description: 'Runtime prompt containing current player input, selected NPCs, memory context, and NPC intent JSON schema.',
    sourceFile: 'src/engine/npc/NpcIntentSimulation.ts',
    sourceSymbol: 'buildNpcIntentSimulationMessages',
    usedBy: ['NpcIntentSimulation.executeNpcIntentSimulation'],
    order: 550,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Changing this can break JSON parsing or cause the helper model to leak facts into the main turn.',
  },
  {
    id: 'femaleProfile.inlineProfileSchema',
    category: 'femaleProfile.writeback',
    title: 'Inline female profile schema',
    description: 'npcProfileSuggestions[].femaleProfile schema for writing female profile data with ordinary NPC profile suggestions.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['NarratorResponseParser.parseNarratorResponse', 'NarratorWritebackApplier.applyNarratorWriteback'],
    order: 600,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'femaleProfile.writebackProtocol',
    category: 'femaleProfile.writeback',
    title: 'Female profile writeback protocol',
    description: 'updateNpcFemaleProfile command rules for public female profile and adult private profile fields.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'generateStateWriterContext',
    usedBy: ['NarratorWritebackApplier.applyNarratorWriteback', 'luanshiCommands.validateLuanShiCommand'],
    order: 610,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'femaleProfile.ageGatePrompt',
    category: 'femaleProfile.writeback',
    title: 'Female profile age gate prompt',
    description: 'Prompt-side location of the age gate rule for adult private profile projection and writeback.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'generateStateWriterContext/formatNpcFemaleProfile',
    usedBy: ['PromptComposer.generateStateWriterContext', 'PromptComposer.formatNpcFemaleProfile'],
    order: 620,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'femaleProfile.existingProfileProjection',
    category: 'femaleProfile.writeback',
    title: 'Existing female profile projection',
    description: 'Projection of existing femaleProfile and adultPrivateProfile fields into the main prompt when allowed.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'formatNpcFemaleProfile',
    usedBy: ['PromptComposer.formatNpcNarrative', 'PromptComposer.formatNpcStateWriterLine'],
    order: 630,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
  },
  {
    id: 'femaleProfile.openingFemaleNpcProfileProtocol',
    category: 'femaleProfile.writeback',
    title: 'Opening female NPC profile protocol',
    description: 'True opening instruction requiring eligible female NPCs to carry complete female profile data with stable npcId reuse.',
    sourceFile: 'src/engine/opening/TrueOpeningGenerator.ts',
    sourceSymbol: 'buildOpeningPlayerInput',
    usedBy: ['TrueOpeningGenerator.generateTrueOpening'],
    order: 640,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'nsfw.adultIntimacy.commonProtocol',
    category: 'nsfw.adultIntimacy',
    title: 'Adult intimacy adaptive scene protocol',
    description: 'Unified adaptive prose guidance for adult scenes after existing gates and relationship conditions allow them.',
    sourceFile: 'src/engine/prompts/PromptContentTemplates.ts',
    sourceSymbol: 'ADULT_INTIMACY_COMMON_PROTOCOL_TEMPLATE',
    usedBy: ['PromptComposer.composePrompt'],
    order: 660,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: false,
  },
  {
    id: 'map.currentMapContext',
    category: 'map.writeback',
    title: 'Current map context projection',
    description: 'Projection of current path, place, scene, nearby routes, travel time, and route risk.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'buildMapNarrativeContext',
    usedBy: ['PromptComposer.generateNarrativeContext'],
    order: 700,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: true,
  },
  {
    id: 'map.writebackProtocol',
    category: 'map.writeback',
    title: 'Map V1 writeback protocol',
    description: 'Map V1 protocol rules for canonical persistent location identity and route writeback.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'appendMapV1WritebackRules',
    usedBy: ['PromptComposer.composePrompt', 'PromptComposer.generateStateWriterContext'],
    order: 710,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    worldbookBound: true,
  },
  {
    id: 'map.locationWritebackSchema',
    category: 'map.writeback',
    title: 'Location writeback schema',
    description: 'writeback.locationWriteSuggestions canonical schema with locationId, aliases, kind, mapLayer, and parentId.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['NarratorResponseParser.parseNarratorResponse', 'NarratorWritebackApplier.applyNarratorWriteback'],
    order: 720,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    worldbookBound: true,
  },
  {
    id: 'map.routeWritebackSchema',
    category: 'map.writeback',
    title: 'Route writeback schema',
    description: 'writeback.routeWriteSuggestions schema for route travel time, risk, notes, and route status.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['NarratorResponseParser.parseNarratorResponse', 'NarratorWritebackApplier.applyNarratorWriteback'],
    order: 730,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    worldbookBound: true,
  },
  {
    id: 'memory.contextProjection',
    category: 'memory.contextProjection',
    title: 'Layered memory context projection',
    description: 'Formats recent raw story, recent summaries, mid-term summaries, long-term facts, NPC summaries, location summaries, and retrieved memories.',
    sourceFile: 'src/engine/memory/MemoryContextPackage.ts',
    sourceSymbol: 'formatMemoryContextPackageForPrompt',
    usedBy: ['PromptComposer.generateNarrativeContext'],
    order: 800,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
  },
  {
    id: 'memory.npcMemoryProjection',
    category: 'memory.contextProjection',
    title: 'NPC memory projection',
    description: 'Formats selected present and focused NPC memories for the main prompt.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'formatNpcMemoryProjection',
    usedBy: ['PromptComposer.generateNarrativeContext'],
    order: 810,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
  },
  {
    id: 'memory.turnSummaryWritebackSchema',
    category: 'memory.contextProjection',
    title: 'Turn summary writeback schema',
    description: 'writeback.turnSummary schema used to store recent turn memory summaries.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['NarratorResponseParser.parseNarratorResponse', 'NarratorWritebackApplier.applyNarratorWriteback'],
    order: 820,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'memory.protagonistMemoryWritebackSchema',
    category: 'memory.contextProjection',
    title: 'Protagonist memory writeback schema',
    description: 'writeback.protagonistMemory schema used to update protagonist behavior memory.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['NarratorResponseParser.parseNarratorResponse', 'NarratorWritebackApplier.applyNarratorWriteback'],
    order: 830,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'memory.summaryCompressionPrompt',
    category: 'memory.summaryCompression',
    title: 'Memory summary compression prompt',
    description: 'LLM prompt pair that compresses recent turn memory into mid-term summaries, long-term facts, NPC summaries, and location summaries.',
    sourceFile: 'src/engine/memory/MemorySummaryExecution.ts',
    sourceSymbol: 'buildMemorySummaryCompressionMessages',
    usedBy: ['MemorySummaryExecution.executeMemorySummaryCompression'],
    order: 900,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
    notes: 'Registry keeps source metadata only; JSON schema stays in MemorySummaryExecution.',
  },
  {
    id: 'memory.summaryCompressionSystemPrompt',
    category: 'memory.summaryCompression',
    title: 'Memory compression system prompt',
    description: 'System message for the dedicated memory compression LLM task.',
    sourceFile: 'src/engine/memory/MemorySummaryExecution.ts',
    sourceSymbol: 'buildMemorySummaryCompressionMessages',
    usedBy: ['MemorySummaryExecution.executeMemorySummaryCompression'],
    order: 910,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'memory.summaryCompressionUserPrompt',
    category: 'memory.summaryCompression',
    title: 'Memory compression user prompt',
    description: 'User message for the memory compression task, including output JSON schema and compression input.',
    sourceFile: 'src/engine/memory/MemorySummaryExecution.ts',
    sourceSymbol: 'buildMemorySummaryCompressionMessages',
    usedBy: ['MemorySummaryExecution.executeMemorySummaryCompression'],
    order: 920,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'memory.embeddingInputText',
    category: 'memory.contextProjection',
    title: 'Memory embedding input text',
    description: 'Text assembled from layered memory sources and submitted to the embedding API for vector indexing.',
    sourceFile: 'src/engine/memory/MemoryEmbeddingIndex.ts',
    sourceSymbol: 'buildMemoryEmbeddingIndexItems',
    usedBy: ['MemoryEmbeddingIndexRefresh.refreshMemoryEmbeddingIndex'],
    order: 930,
    riskLevel: 'medium',
    editLevel: 'advanced',
    runtimeUsed: true,
    protocolBound: false,
    notes: 'This is embedding input, not a generative prompt.',
  },
  {
    id: 'worldbook.timelineAnchors',
    category: 'worldbook.prompts',
    title: 'Worldbook timeline anchors',
    description: 'Era anchor summaries injected into the main system prompt.',
    sourceFile: 'src/worldbooks/threeKingdoms/timelineAnchors.ts',
    usedBy: ['PromptComposer.composePrompt'],
    order: 1000,
    riskLevel: 'low',
    editLevel: 'safe',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: true,
  },
  {
    id: 'worldbook.openingCrisis',
    category: 'worldbook.prompts',
    title: 'Worldbook opening crisis',
    description: 'Opening crisis template used to frame the first playable scene and immediate pressure.',
    sourceFile: 'src/worldbooks/threeKingdoms/openingCrisisTemplates.ts',
    usedBy: ['PromptComposer.composePrompt', 'TrueOpeningGenerator.generateTrueOpening'],
    order: 1010,
    riskLevel: 'low',
    editLevel: 'safe',
    runtimeUsed: true,
    protocolBound: false,
    worldbookBound: true,
  },
  {
    id: 'world.worldEventWriteback',
    category: 'main.userProtocol',
    title: 'World event writeback schema',
    description: 'writeback.worldEventSummary schema for world event memory suggestions.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['NarratorResponseParser.parseNarratorResponse', 'NarratorWritebackApplier.applyNarratorWriteback'],
    order: 1100,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'dynamic.currentMatterProtocol',
    category: 'main.userProtocol',
    title: 'Current matter writeback protocol',
    description: 'questAdded and questUpdated protocol for player-facing current matters, commitments, stakes, and deadlines.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'generateStateWriterContext',
    usedBy: ['PromptComposer.composePrompt', 'StatePatchValidator.validatePatch', 'StatePatchApplier.applyPatch'],
    order: 1105,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'dynamic.signalProtocol',
    category: 'main.userProtocol',
    title: 'Signal writeback protocol',
    description: 'rumorAdded protocol for player-known rumors, clues, reports, potential consequences, and follow-up hooks.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'generateStateWriterContext',
    usedBy: ['PromptComposer.composePrompt', 'StatePatchValidator.validatePatch', 'StatePatchApplier.applyPatch'],
    order: 1106,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'world.plotPlanSuggestions',
    category: 'main.userProtocol',
    title: 'Plot plan suggestion schema',
    description: 'writeback.plotPlanSuggestions schema for medium-term plot plan suggestions.',
    sourceFile: 'src/engine/turn/PromptComposer.ts',
    sourceSymbol: 'composePrompt',
    usedBy: ['NarratorResponseParser.parseNarratorResponse'],
    order: 1110,
    riskLevel: 'high',
    editLevel: 'locked',
    runtimeUsed: true,
    protocolBound: true,
  },
  {
    id: 'settings.apiTaskDescriptions',
    category: 'settings.taskDescriptions',
    title: 'API task descriptions',
    description: 'Task routing labels and descriptions for main narrative, memory summary, embedding, NPC completion, and future tasks.',
    sourceFile: 'src/engine/settings/ApiConfigManager.ts',
    sourceSymbol: 'API_TASKS',
    usedBy: ['ApiSettingsPanel', 'settingsPanelModel'],
    order: 1200,
    riskLevel: 'low',
    editLevel: 'safe',
    runtimeUsed: false,
    protocolBound: false,
    notes: 'UI/config metadata only; not sent to an LLM as prompt text.',
  },
  {
    id: 'settings.functionConfigDescriptions',
    category: 'settings.taskDescriptions',
    title: 'Function config descriptions',
    description: 'Settings panel descriptions for memory, vector retrieval, NPC profile completion, and planned NPC simulation configuration.',
    sourceFile: 'src/ui/settingsPanelModel.ts',
    sourceSymbol: 'FUNCTION_CONFIG_PANELS',
    usedBy: ['ApiSettingsPanel'],
    order: 1210,
    riskLevel: 'low',
    editLevel: 'safe',
    runtimeUsed: false,
    protocolBound: false,
    notes: 'UI metadata only; included for future prompt/settings management discovery.',
  },
  {
    id: 'docs.promptResponseProtocol',
    category: 'settings.taskDescriptions',
    title: 'Prompt response protocol document',
    description: 'Design document describing the main turn JSON response protocol and writeback discipline.',
    sourceFile: 'docs/PROMPT_RESPONSE_PROTOCOL_V1.md',
    usedBy: ['developer documentation'],
    order: 1220,
    riskLevel: 'low',
    editLevel: 'safe',
    runtimeUsed: false,
    protocolBound: true,
    notes: 'Documentation entry only; not runtime prompt content.',
  },
  {
    id: 'docs.promptModuleArchitecture',
    category: 'settings.taskDescriptions',
    title: 'Prompt module architecture document',
    description: 'Design document describing prompt module layers, token budget, and conditional protocol direction.',
    sourceFile: 'docs/superpowers/specs/2026-06-16-prompt-module-architecture-design.md',
    usedBy: ['developer documentation'],
    order: 1230,
    riskLevel: 'low',
    editLevel: 'safe',
    runtimeUsed: false,
    protocolBound: false,
    notes: 'Documentation entry only; useful for future read-only settings display.',
  },
];

export function getPromptRegistry(): PromptRegistryEntry[] {
  return promptRegistry.map((entry) => ({
    ...entry,
    ...PROMPT_CONTENT_VIEWS[entry.id],
    usedBy: [...entry.usedBy],
  }));
}

export function isRuntimeOverridePromptId(promptId: string): boolean {
  return runtimeOverridePromptIds.has(promptId);
}

export function isRuntimeOverridePromptEntry(entry: PromptRegistryEntry): boolean {
  return entry.runtimeUsed && isRuntimeOverridePromptId(entry.id);
}
